// Generated by `wit-bindgen` 0.48.1. DO NOT EDIT!
#ifndef __BINDINGS_DEMO_EXTENSION_H
#define __BINDINGS_DEMO_EXTENSION_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct demo_extension_string_t {
  uint8_t*ptr;
  size_t len;
} demo_extension_string_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} demo_extension_list_u8_t;

// Unified SQL value representation. Used for function arguments,
// function results, parameter binding, and row data.
typedef struct sqlite_extension_types_sql_value_t {
  uint8_t tag;
  union {
    int64_t     integer;
    double     real;
    demo_extension_string_t     text;
    demo_extension_list_u8_t     blob;
  } val;
} sqlite_extension_types_sql_value_t;

// SQL NULL.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_NULL 0
// Signed 64-bit integer.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_INTEGER 1
// IEEE 754 double-precision floating point.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_REAL 2
// UTF-8 text.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_TEXT 3
// Binary blob.
#define SQLITE_EXTENSION_TYPES_SQL_VALUE_BLOB 4

// SQLite error carrying both primary and extended result codes.
typedef struct sqlite_extension_types_sqlite_error_t {
  int32_t   code;
  int32_t   extended_code;
  demo_extension_string_t   message;
} sqlite_extension_types_sqlite_error_t;

// Flags describing a SQL function's properties. Mirror SQLite's
// SQLITE_DETERMINISTIC / SQLITE_DIRECTONLY / SQLITE_INNOCUOUS bits.
typedef uint8_t sqlite_extension_types_function_flags_t;

// Same inputs always produce the same output.
#define SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_DETERMINISTIC (1 << 0)
// May have side effects; cannot be used in indexes, CHECK
// constraints, generated columns, etc.
#define SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_DIRECT_ONLY (1 << 1)
// Function is provably safe to use in arbitrary trusted SQL.
#define SQLITE_EXTENSION_TYPES_FUNCTION_FLAGS_INNOCUOUS (1 << 2)

// Authorization action codes. Mirrors SQLite's SQLITE_* action
// constants passed to the authorizer callback.
typedef uint8_t sqlite_extension_types_auth_action_t;

#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_INDEX 0
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TABLE 1
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_INDEX 2
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_TABLE 3
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_TRIGGER 4
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TEMP_VIEW 5
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_TRIGGER 6
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_VIEW 7
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DELETE 8
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_INDEX 9
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TABLE 10
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_INDEX 11
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_TABLE 12
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_TRIGGER 13
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TEMP_VIEW 14
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_TRIGGER 15
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_VIEW 16
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_INSERT 17
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_PRAGMA 18
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_READ 19
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_SELECT 20
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_TRANSACTION 21
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_UPDATE 22
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_ATTACH 23
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DETACH 24
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_ALTER_TABLE 25
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_REINDEX 26
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_ANALYZE 27
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_CREATE_VTABLE 28
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_DROP_VTABLE 29
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_FUNCTION 30
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_SAVEPOINT 31
#define SQLITE_EXTENSION_TYPES_AUTH_ACTION_RECURSIVE 32

// Result returned from an authorizer callback.
typedef uint8_t sqlite_extension_types_auth_result_t;

// Permit the action.
#define SQLITE_EXTENSION_TYPES_AUTH_RESULT_OK 0
// Deny the action with an error.
#define SQLITE_EXTENSION_TYPES_AUTH_RESULT_DENY 1
// Silently ignore the action (treat as no-op).
#define SQLITE_EXTENSION_TYPES_AUTH_RESULT_IGNORE 2

// Type of row change reported to an update hook.
typedef uint8_t sqlite_extension_types_update_operation_t;

#define SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_INSERT 0
#define SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_UPDATE 1
#define SQLITE_EXTENSION_TYPES_UPDATE_OPERATION_DELETE 2

// Log severity levels.
typedef uint8_t sqlite_extension_types_log_level_t;

#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_ERROR 0
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_WARN 1
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_INFO 2
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_DEBUG 3
#define SQLITE_EXTENSION_TYPES_LOG_LEVEL_TRACE 4

typedef struct {
  bool is_some;
  demo_extension_string_t val;
} demo_extension_option_string_t;

// Per-column metadata returned by schema introspection.
typedef struct sqlite_extension_types_column_info_t {
  demo_extension_string_t   name;
  demo_extension_option_string_t   decl_type;
  demo_extension_option_string_t   database;
  demo_extension_option_string_t   table;
  demo_extension_option_string_t   origin;
} sqlite_extension_types_column_info_t;

typedef struct {
  sqlite_extension_types_column_info_t *ptr;
  size_t len;
} sqlite_extension_types_list_column_info_t;

typedef struct {
  demo_extension_string_t *ptr;
  size_t len;
} demo_extension_list_string_t;

// Per-table metadata returned by schema introspection.
typedef struct sqlite_extension_types_table_info_t {
  demo_extension_string_t   name;
  sqlite_extension_types_list_column_info_t   columns;
  demo_extension_list_string_t   pk_columns;
} sqlite_extension_types_table_info_t;

typedef struct {
  sqlite_extension_types_sql_value_t *ptr;
  size_t len;
} sqlite_extension_types_list_sql_value_t;

typedef struct {
  sqlite_extension_types_list_sql_value_t *ptr;
  size_t len;
} sqlite_extension_types_list_list_sql_value_t;

// Result of an `execute` call: column names, row data, change counts.
typedef struct sqlite_extension_types_query_result_t {
  demo_extension_list_string_t   columns;
  sqlite_extension_types_list_list_sql_value_t   rows;
  // Rows changed by INSERT/UPDATE/DELETE.
  int64_t   changes;
  // Last inserted rowid.
  int64_t   last_insert_rowid;
} sqlite_extension_types_query_result_t;

// HTTP method. Mirrors `wasi:http/types.method`.
typedef struct sqlite_extension_http_method_t {
  uint8_t tag;
  union {
    demo_extension_string_t     other;
  } val;
} sqlite_extension_http_method_t;

#define SQLITE_EXTENSION_HTTP_METHOD_GET 0
#define SQLITE_EXTENSION_HTTP_METHOD_HEAD 1
#define SQLITE_EXTENSION_HTTP_METHOD_POST 2
#define SQLITE_EXTENSION_HTTP_METHOD_PUT 3
#define SQLITE_EXTENSION_HTTP_METHOD_DELETE 4
#define SQLITE_EXTENSION_HTTP_METHOD_CONNECT 5
#define SQLITE_EXTENSION_HTTP_METHOD_OPTIONS 6
#define SQLITE_EXTENSION_HTTP_METHOD_TRACE 7
#define SQLITE_EXTENSION_HTTP_METHOD_PATCH 8
// Non-standard / extension method.
#define SQLITE_EXTENSION_HTTP_METHOD_OTHER 9

// URL scheme. Mirrors `wasi:http/types.scheme`.
typedef struct sqlite_extension_http_scheme_t {
  uint8_t tag;
  union {
    demo_extension_string_t     other;
  } val;
} sqlite_extension_http_scheme_t;

#define SQLITE_EXTENSION_HTTP_SCHEME_HTTP 0
#define SQLITE_EXTENSION_HTTP_SCHEME_HTTPS 1
// Non-standard scheme.
#define SQLITE_EXTENSION_HTTP_SCHEME_OTHER 2

// Header field — name + raw bytes value (per wasi-http).
typedef struct sqlite_extension_http_field_t {
  demo_extension_string_t   f0;
  demo_extension_list_u8_t   f1;
} sqlite_extension_http_field_t;

typedef struct {
  bool is_some;
  sqlite_extension_http_scheme_t val;
} sqlite_extension_http_option_scheme_t;

typedef struct {
  sqlite_extension_http_field_t *ptr;
  size_t len;
} demo_extension_list_field_t;

typedef struct {
  bool is_some;
  demo_extension_list_u8_t val;
} demo_extension_option_list_u8_t;

typedef struct {
  bool is_some;
  uint32_t val;
} demo_extension_option_u32_t;

// Outgoing request. Mirrors `wasi:http/types.outgoing-request`
// but flattened from the resource-based wasi-http form into a
// single value-typed record.
typedef struct sqlite_extension_http_request_t {
  sqlite_extension_http_method_t   method;
  sqlite_extension_http_option_scheme_t   scheme;
  // Host (with optional port), e.g. "example.com:8443".
  demo_extension_option_string_t   authority;
  // Path + query, e.g. "/api/v1/things?id=42".
  demo_extension_option_string_t   path_with_query;
  demo_extension_list_field_t   headers;
  demo_extension_option_list_u8_t   body;
  demo_extension_option_u32_t   timeout_ms;
} sqlite_extension_http_request_t;

// Incoming response. Mirrors `wasi:http/types.incoming-response`
// in flattened form.
typedef struct sqlite_extension_http_response_t {
  uint16_t   status;
  demo_extension_list_field_t   headers;
  demo_extension_list_u8_t   body;
} sqlite_extension_http_response_t;

// HTTP error variants. Mirrors the shape of
// `wasi:http/types.error-code` at a higher level.
typedef struct sqlite_extension_http_http_error_t {
  uint8_t tag;
  union {
    demo_extension_string_t     invalid_url;
    demo_extension_string_t     connection_error;
    demo_extension_string_t     protocol_error;
    demo_extension_string_t     other;
  } val;
} sqlite_extension_http_http_error_t;

#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_INVALID_URL 0
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_TIMED_OUT 1
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_CONNECTION_ERROR 2
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_PROTOCOL_ERROR 3
#define SQLITE_EXTENSION_HTTP_HTTP_ERROR_OTHER 4

typedef struct {
  bool is_err;
  union {
    sqlite_extension_http_response_t ok;
    sqlite_extension_http_http_error_t err;
  } val;
} sqlite_extension_http_result_response_http_error_t;

typedef sqlite_extension_http_method_t sqlite_extension_policy_method_t;

// One capability per host-imported interface.
typedef struct sqlite_extension_policy_capability_t {
  uint8_t tag;
} sqlite_extension_policy_capability_t;

// Basic SQL execution (sqlite:extension/spi).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_SPI 0
// Prepared statement handles (sqlite:extension/prepared).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_PREPARED 1
// Transaction control (sqlite:extension/transaction). Mutating.
#define SQLITE_EXTENSION_POLICY_CAPABILITY_TRANSACTION 2
// Schema introspection (sqlite:extension/schema).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_SCHEMA 3
// Persistent per-extension state (sqlite:extension/state).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_STATE 4
// Bounded in-memory cache (sqlite:extension/cache).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_CACHE 5
// Random number generation (sqlite:extension/random).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_RANDOM 6
// Unicode text utilities (sqlite:extension/text).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_TEXT 7
// Cryptographic hashing (sqlite:extension/hashing).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_HASHING 8
// Encoding helpers (sqlite:extension/encoding).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_ENCODING 9
// Outbound HTTP (sqlite:extension/http).
#define SQLITE_EXTENSION_POLICY_CAPABILITY_HTTP 10

typedef struct {
  sqlite_extension_policy_method_t *ptr;
  size_t len;
} sqlite_extension_policy_list_method_t;

typedef struct {
  bool is_some;
  sqlite_extension_policy_list_method_t val;
} sqlite_extension_policy_option_list_method_t;

typedef struct {
  bool is_some;
  uint64_t val;
} demo_extension_option_u64_t;

// Outbound HTTP policy. Applied by the host's `http::handle`
// implementation to every request the extension makes.
typedef struct sqlite_extension_policy_http_policy_t {
  // Allowlist of hostnames the extension may connect to. Entries
  // may use a leading `*.` for a wildcard suffix. Empty list
  // means no hosts permitted.
  demo_extension_list_string_t   allowed_hosts;
  // Optional method restriction. None = any method allowed.
  sqlite_extension_policy_option_list_method_t   allowed_methods;
  // Maximum response body bytes the host will return to the
  // extension. Larger responses are truncated or errored.
  demo_extension_option_u64_t   max_body_bytes;
  // Per-request wall-clock timeout. Overrides any timeout the
  // extension passes in the request.
  demo_extension_option_u32_t   timeout_ms;
} sqlite_extension_policy_http_policy_t;

// Filesystem policy. Reserved for future use; no host interfaces
// currently grant fs access. The shape is sketched so consumers
// can prepare for it.
typedef struct sqlite_extension_policy_fs_policy_t {
  // Allowlist of host-path prefixes the extension may read from.
  demo_extension_list_string_t   readable_prefixes;
  // Allowlist of host-path prefixes the extension may write to.
  demo_extension_list_string_t   writable_prefixes;
  // Cap on cumulative bytes the extension may write per call.
  demo_extension_option_u64_t   max_write_bytes_per_call;
} sqlite_extension_policy_fs_policy_t;

typedef struct {
  bool is_some;
  sqlite_extension_policy_http_policy_t val;
} sqlite_extension_policy_option_http_policy_t;

typedef struct {
  bool is_some;
  sqlite_extension_policy_fs_policy_t val;
} sqlite_extension_policy_option_fs_policy_t;

typedef struct {
  sqlite_extension_policy_capability_t *ptr;
  size_t len;
} sqlite_extension_policy_list_capability_t;

// Options the host passes at load time.
typedef struct sqlite_extension_policy_load_options_t {
  // wasmtime fuel budget. Reset before each guest invocation
  // (per-call semantics). None = unlimited.
  demo_extension_option_u64_t   fuel_per_call;
  // Hard cap on the extension's linear memory in bytes.
  demo_extension_option_u64_t   memory_limit_bytes;
  // Wall-clock deadline per guest invocation. Enforced via
  // epoch interruption on runtimes that support it; advisory
  // only on those that don't.
  demo_extension_option_u64_t   epoch_deadline_ms;
  // HTTP policy. Required if `grant` contains `capability::http`.
  sqlite_extension_policy_option_http_policy_t   http_policy;
  // Filesystem policy. Reserved.
  sqlite_extension_policy_option_fs_policy_t   fs_policy;
  // Allow-list of capabilities granted to this extension.
  // Anything not in this list is denied. Fail-closed.
  sqlite_extension_policy_list_capability_t   grant;
} sqlite_extension_policy_load_options_t;

// Errors a loader may raise when policy refuses a load or call.
typedef struct sqlite_extension_policy_policy_error_t {
  uint8_t tag;
  union {
    sqlite_extension_policy_capability_t     capability_not_granted;
    sqlite_extension_policy_capability_t     capability_not_declared;
    demo_extension_string_t     host_not_allowed;
    sqlite_extension_policy_method_t     method_not_allowed;
  } val;
} sqlite_extension_policy_policy_error_t;

// Extension declared a capability the host did not grant.
// The variant payload is the missing capability.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_CAPABILITY_NOT_GRANTED 0
// Extension tried to use a capability it never declared.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_CAPABILITY_NOT_DECLARED 1
// An HTTP request was refused by `http-policy.allowed-hosts`.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_HOST_NOT_ALLOWED 2
// An HTTP request used a method outside `allowed-methods`.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_METHOD_NOT_ALLOWED 3
// `grant` includes `http` but `http-policy` was None.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_MISSING_HTTP_POLICY 4
// Resource limit reached.
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_FUEL_EXHAUSTED 5
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_MEMORY_LIMIT_EXCEEDED 6
#define SQLITE_EXTENSION_POLICY_POLICY_ERROR_EPOCH_DEADLINE_EXCEEDED 7

typedef sqlite_extension_types_function_flags_t sqlite_extension_metadata_function_flags_t;

typedef sqlite_extension_policy_capability_t sqlite_extension_metadata_capability_t;

// One scalar SQL function declared by the extension.
typedef struct sqlite_extension_metadata_scalar_function_spec_t {
  // Guest-assigned function ID. Echoed back in scalar-function.call.
  uint64_t   id;
  // SQL name visible inside the database.
  demo_extension_string_t   name;
  // Number of arguments; -1 means variadic.
  int32_t   num_args;
  sqlite_extension_metadata_function_flags_t   func_flags;
} sqlite_extension_metadata_scalar_function_spec_t;

// One aggregate (or window) SQL function declared by the extension.
typedef struct sqlite_extension_metadata_aggregate_function_spec_t {
  uint64_t   id;
  demo_extension_string_t   name;
  int32_t   num_args;
  sqlite_extension_metadata_function_flags_t   func_flags;
  // True if this aggregate also implements window-function ops
  // (value() + inverse()).
  bool   is_window;
} sqlite_extension_metadata_aggregate_function_spec_t;

// One custom collation declared by the extension.
typedef struct sqlite_extension_metadata_collation_spec_t {
  uint64_t   id;
  demo_extension_string_t   name;
} sqlite_extension_metadata_collation_spec_t;

typedef struct {
  sqlite_extension_metadata_scalar_function_spec_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_scalar_function_spec_t;

typedef struct {
  sqlite_extension_metadata_aggregate_function_spec_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_aggregate_function_spec_t;

typedef struct {
  sqlite_extension_metadata_collation_spec_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_collation_spec_t;

typedef struct {
  sqlite_extension_metadata_capability_t *ptr;
  size_t len;
} sqlite_extension_metadata_list_capability_t;

// Full extension manifest, returned from `describe()`.
typedef struct sqlite_extension_metadata_manifest_t {
  demo_extension_string_t   name;
  demo_extension_string_t   version;
  sqlite_extension_metadata_list_scalar_function_spec_t   scalar_functions;
  sqlite_extension_metadata_list_aggregate_function_spec_t   aggregate_functions;
  sqlite_extension_metadata_list_collation_spec_t   collations;
  // True if the extension also exports an `authorizer` interface.
  bool   has_authorizer;
  // True if the extension also exports an `update-hook` interface.
  bool   has_update_hook;
  // True if the extension also exports a `commit-hook` interface.
  bool   has_commit_hook;
  // REQUIRED: every host capability the extension imports MUST be
  // listed here. The loader compares this against
  // `load-options.grant` and refuses to load if any item is
  // missing from the grant list. Empty list = no host
  // capabilities used (extension is pure / only uses its own
  // allocator).
  sqlite_extension_metadata_list_capability_t   declared_capabilities;
} sqlite_extension_metadata_manifest_t;

typedef sqlite_extension_types_sql_value_t exports_sqlite_wasm_demo_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t exports_sqlite_wasm_demo_slot_manifest_t;

typedef struct {
  exports_sqlite_wasm_demo_slot_sql_value_t *ptr;
  size_t len;
} exports_sqlite_wasm_demo_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_demo_slot_sql_value_t ok;
    demo_extension_string_t err;
  } val;
} exports_sqlite_wasm_demo_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t exports_sqlite_wasm_fts5_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t exports_sqlite_wasm_fts5_slot_manifest_t;

typedef struct {
  exports_sqlite_wasm_fts5_slot_sql_value_t *ptr;
  size_t len;
} exports_sqlite_wasm_fts5_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_fts5_slot_sql_value_t ok;
    demo_extension_string_t err;
  } val;
} exports_sqlite_wasm_fts5_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t exports_sqlite_wasm_json1_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t exports_sqlite_wasm_json1_slot_manifest_t;

typedef struct {
  exports_sqlite_wasm_json1_slot_sql_value_t *ptr;
  size_t len;
} exports_sqlite_wasm_json1_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_json1_slot_sql_value_t ok;
    demo_extension_string_t err;
  } val;
} exports_sqlite_wasm_json1_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t exports_sqlite_wasm_rtree_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t exports_sqlite_wasm_rtree_slot_manifest_t;

typedef struct {
  exports_sqlite_wasm_rtree_slot_sql_value_t *ptr;
  size_t len;
} exports_sqlite_wasm_rtree_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_rtree_slot_sql_value_t ok;
    demo_extension_string_t err;
  } val;
} exports_sqlite_wasm_rtree_slot_result_sql_value_string_t;

typedef sqlite_extension_types_sql_value_t exports_sqlite_wasm_geopoly_slot_sql_value_t;

typedef sqlite_extension_metadata_manifest_t exports_sqlite_wasm_geopoly_slot_manifest_t;

typedef struct {
  exports_sqlite_wasm_geopoly_slot_sql_value_t *ptr;
  size_t len;
} exports_sqlite_wasm_geopoly_slot_list_sql_value_t;

typedef struct {
  bool is_err;
  union {
    exports_sqlite_wasm_geopoly_slot_sql_value_t ok;
    demo_extension_string_t err;
  } val;
} exports_sqlite_wasm_geopoly_slot_result_sql_value_string_t;

// Imported Functions from `sqlite:extension/http@0.1.0`
// Send the request and wait for the full response.
extern bool sqlite_extension_http_handle(sqlite_extension_http_request_t *req, sqlite_extension_http_response_t *ret, sqlite_extension_http_http_error_t *err);

// Imported Functions from `sqlite:extension/metadata@0.1.0`
// Return the extension's full manifest. Called once by the host
// after instantiation, before any other guest function is dispatched.
extern void sqlite_extension_metadata_describe(sqlite_extension_metadata_manifest_t *ret);

// Exported Functions from `sqlite:wasm/demo-slot@0.1.0`
void exports_sqlite_wasm_demo_slot_describe(exports_sqlite_wasm_demo_slot_manifest_t *ret);
bool exports_sqlite_wasm_demo_slot_call(uint64_t func_id, exports_sqlite_wasm_demo_slot_list_sql_value_t *args, exports_sqlite_wasm_demo_slot_sql_value_t *ret, demo_extension_string_t *err);

// Exported Functions from `sqlite:wasm/fts5-slot@0.1.0`
void exports_sqlite_wasm_fts5_slot_describe(exports_sqlite_wasm_fts5_slot_manifest_t *ret);
bool exports_sqlite_wasm_fts5_slot_call(uint64_t func_id, exports_sqlite_wasm_fts5_slot_list_sql_value_t *args, exports_sqlite_wasm_fts5_slot_sql_value_t *ret, demo_extension_string_t *err);

// Exported Functions from `sqlite:wasm/json1-slot@0.1.0`
void exports_sqlite_wasm_json1_slot_describe(exports_sqlite_wasm_json1_slot_manifest_t *ret);
bool exports_sqlite_wasm_json1_slot_call(uint64_t func_id, exports_sqlite_wasm_json1_slot_list_sql_value_t *args, exports_sqlite_wasm_json1_slot_sql_value_t *ret, demo_extension_string_t *err);

// Exported Functions from `sqlite:wasm/rtree-slot@0.1.0`
void exports_sqlite_wasm_rtree_slot_describe(exports_sqlite_wasm_rtree_slot_manifest_t *ret);
bool exports_sqlite_wasm_rtree_slot_call(uint64_t func_id, exports_sqlite_wasm_rtree_slot_list_sql_value_t *args, exports_sqlite_wasm_rtree_slot_sql_value_t *ret, demo_extension_string_t *err);

// Exported Functions from `sqlite:wasm/geopoly-slot@0.1.0`
void exports_sqlite_wasm_geopoly_slot_describe(exports_sqlite_wasm_geopoly_slot_manifest_t *ret);
bool exports_sqlite_wasm_geopoly_slot_call(uint64_t func_id, exports_sqlite_wasm_geopoly_slot_list_sql_value_t *args, exports_sqlite_wasm_geopoly_slot_sql_value_t *ret, demo_extension_string_t *err);

// Helper Functions

void demo_extension_list_u8_free(demo_extension_list_u8_t *ptr);

void sqlite_extension_types_sql_value_free(sqlite_extension_types_sql_value_t *ptr);

void sqlite_extension_types_sqlite_error_free(sqlite_extension_types_sqlite_error_t *ptr);

void demo_extension_option_string_free(demo_extension_option_string_t *ptr);

void sqlite_extension_types_column_info_free(sqlite_extension_types_column_info_t *ptr);

void sqlite_extension_types_list_column_info_free(sqlite_extension_types_list_column_info_t *ptr);

void demo_extension_list_string_free(demo_extension_list_string_t *ptr);

void sqlite_extension_types_table_info_free(sqlite_extension_types_table_info_t *ptr);

void sqlite_extension_types_list_sql_value_free(sqlite_extension_types_list_sql_value_t *ptr);

void sqlite_extension_types_list_list_sql_value_free(sqlite_extension_types_list_list_sql_value_t *ptr);

void sqlite_extension_types_query_result_free(sqlite_extension_types_query_result_t *ptr);

void sqlite_extension_http_method_free(sqlite_extension_http_method_t *ptr);

void sqlite_extension_http_scheme_free(sqlite_extension_http_scheme_t *ptr);

void sqlite_extension_http_field_free(sqlite_extension_http_field_t *ptr);

void sqlite_extension_http_option_scheme_free(sqlite_extension_http_option_scheme_t *ptr);

void demo_extension_list_field_free(demo_extension_list_field_t *ptr);

void demo_extension_option_list_u8_free(demo_extension_option_list_u8_t *ptr);

void demo_extension_option_u32_free(demo_extension_option_u32_t *ptr);

void sqlite_extension_http_request_free(sqlite_extension_http_request_t *ptr);

void sqlite_extension_http_response_free(sqlite_extension_http_response_t *ptr);

void sqlite_extension_http_http_error_free(sqlite_extension_http_http_error_t *ptr);

void sqlite_extension_http_result_response_http_error_free(sqlite_extension_http_result_response_http_error_t *ptr);

void sqlite_extension_policy_method_free(sqlite_extension_policy_method_t *ptr);

void sqlite_extension_policy_capability_free(sqlite_extension_policy_capability_t *ptr);

void sqlite_extension_policy_list_method_free(sqlite_extension_policy_list_method_t *ptr);

void sqlite_extension_policy_option_list_method_free(sqlite_extension_policy_option_list_method_t *ptr);

void demo_extension_option_u64_free(demo_extension_option_u64_t *ptr);

void sqlite_extension_policy_http_policy_free(sqlite_extension_policy_http_policy_t *ptr);

void sqlite_extension_policy_fs_policy_free(sqlite_extension_policy_fs_policy_t *ptr);

void sqlite_extension_policy_option_http_policy_free(sqlite_extension_policy_option_http_policy_t *ptr);

void sqlite_extension_policy_option_fs_policy_free(sqlite_extension_policy_option_fs_policy_t *ptr);

void sqlite_extension_policy_list_capability_free(sqlite_extension_policy_list_capability_t *ptr);

void sqlite_extension_policy_load_options_free(sqlite_extension_policy_load_options_t *ptr);

void sqlite_extension_policy_policy_error_free(sqlite_extension_policy_policy_error_t *ptr);

void sqlite_extension_metadata_capability_free(sqlite_extension_metadata_capability_t *ptr);

void sqlite_extension_metadata_scalar_function_spec_free(sqlite_extension_metadata_scalar_function_spec_t *ptr);

void sqlite_extension_metadata_aggregate_function_spec_free(sqlite_extension_metadata_aggregate_function_spec_t *ptr);

void sqlite_extension_metadata_collation_spec_free(sqlite_extension_metadata_collation_spec_t *ptr);

void sqlite_extension_metadata_list_scalar_function_spec_free(sqlite_extension_metadata_list_scalar_function_spec_t *ptr);

void sqlite_extension_metadata_list_aggregate_function_spec_free(sqlite_extension_metadata_list_aggregate_function_spec_t *ptr);

void sqlite_extension_metadata_list_collation_spec_free(sqlite_extension_metadata_list_collation_spec_t *ptr);

void sqlite_extension_metadata_list_capability_free(sqlite_extension_metadata_list_capability_t *ptr);

void sqlite_extension_metadata_manifest_free(sqlite_extension_metadata_manifest_t *ptr);

void exports_sqlite_wasm_demo_slot_sql_value_free(exports_sqlite_wasm_demo_slot_sql_value_t *ptr);

void exports_sqlite_wasm_demo_slot_manifest_free(exports_sqlite_wasm_demo_slot_manifest_t *ptr);

void exports_sqlite_wasm_demo_slot_list_sql_value_free(exports_sqlite_wasm_demo_slot_list_sql_value_t *ptr);

void exports_sqlite_wasm_demo_slot_result_sql_value_string_free(exports_sqlite_wasm_demo_slot_result_sql_value_string_t *ptr);

void exports_sqlite_wasm_fts5_slot_sql_value_free(exports_sqlite_wasm_fts5_slot_sql_value_t *ptr);

void exports_sqlite_wasm_fts5_slot_manifest_free(exports_sqlite_wasm_fts5_slot_manifest_t *ptr);

void exports_sqlite_wasm_fts5_slot_list_sql_value_free(exports_sqlite_wasm_fts5_slot_list_sql_value_t *ptr);

void exports_sqlite_wasm_fts5_slot_result_sql_value_string_free(exports_sqlite_wasm_fts5_slot_result_sql_value_string_t *ptr);

void exports_sqlite_wasm_json1_slot_sql_value_free(exports_sqlite_wasm_json1_slot_sql_value_t *ptr);

void exports_sqlite_wasm_json1_slot_manifest_free(exports_sqlite_wasm_json1_slot_manifest_t *ptr);

void exports_sqlite_wasm_json1_slot_list_sql_value_free(exports_sqlite_wasm_json1_slot_list_sql_value_t *ptr);

void exports_sqlite_wasm_json1_slot_result_sql_value_string_free(exports_sqlite_wasm_json1_slot_result_sql_value_string_t *ptr);

void exports_sqlite_wasm_rtree_slot_sql_value_free(exports_sqlite_wasm_rtree_slot_sql_value_t *ptr);

void exports_sqlite_wasm_rtree_slot_manifest_free(exports_sqlite_wasm_rtree_slot_manifest_t *ptr);

void exports_sqlite_wasm_rtree_slot_list_sql_value_free(exports_sqlite_wasm_rtree_slot_list_sql_value_t *ptr);

void exports_sqlite_wasm_rtree_slot_result_sql_value_string_free(exports_sqlite_wasm_rtree_slot_result_sql_value_string_t *ptr);

void exports_sqlite_wasm_geopoly_slot_sql_value_free(exports_sqlite_wasm_geopoly_slot_sql_value_t *ptr);

void exports_sqlite_wasm_geopoly_slot_manifest_free(exports_sqlite_wasm_geopoly_slot_manifest_t *ptr);

void exports_sqlite_wasm_geopoly_slot_list_sql_value_free(exports_sqlite_wasm_geopoly_slot_list_sql_value_t *ptr);

void exports_sqlite_wasm_geopoly_slot_result_sql_value_string_free(exports_sqlite_wasm_geopoly_slot_result_sql_value_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void demo_extension_string_set(demo_extension_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void demo_extension_string_dup(demo_extension_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void demo_extension_string_free(demo_extension_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
