// Generated by `wit-bindgen` 0.48.1. DO NOT EDIT!
#include "demo_extension.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `sqlite:extension/http@0.1.0`

__attribute__((__import_module__("sqlite:extension/http@0.1.0"), __import_name__("handle")))
extern void __wasm_import_sqlite_extension_http_handle(uint8_t *, uint8_t *);

// Imported Functions from `sqlite:extension/metadata@0.1.0`

__attribute__((__import_module__("sqlite:extension/metadata@0.1.0"), __import_name__("describe")))
extern void __wasm_import_sqlite_extension_metadata_describe(uint8_t *);

// Exported Functions from `sqlite:wasm/demo-slot@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/demo-slot@0.1.0#describe")))
void __wasm_export_exports_sqlite_wasm_demo_slot_describe_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
  if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
    free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
  }
  size_t len = *((size_t*) (arg0 + (5*sizeof(void*))));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + (4*sizeof(void*))));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr);
  }
  size_t len0 = *((size_t*) (arg0 + (7*sizeof(void*))));
  if (len0 > 0) {
    uint8_t *ptr1 = *((uint8_t **) (arg0 + (6*sizeof(void*))));
    for (size_t i2 = 0; i2 < len0; i2++) {
      uint8_t *base = ptr1 + i2 * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr1);
  }
  size_t len3 = *((size_t*) (arg0 + (9*sizeof(void*))));
  if (len3 > 0) {
    uint8_t *ptr4 = *((uint8_t **) (arg0 + (8*sizeof(void*))));
    for (size_t i5 = 0; i5 < len3; i5++) {
      uint8_t *base = ptr4 + i5 * (8+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr4);
  }
  size_t len6 = *((size_t*) (arg0 + (12*sizeof(void*))));
  if (len6 > 0) {
    uint8_t *ptr7 = *((uint8_t **) (arg0 + (11*sizeof(void*))));
    for (size_t i8 = 0; i8 < len6; i8++) {
      uint8_t *base = ptr7 + i8 * 1;
      (void) base;
    }
    free(ptr7);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/demo-slot@0.1.0#call")))
void __wasm_export_exports_sqlite_wasm_demo_slot_call_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 8))) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 4: {
          size_t len = *((size_t*) (arg0 + (16+1*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (arg0 + 16));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
          break;
        }
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + 8)));
      }
      break;
    }
  }
}

// Exported Functions from `sqlite:wasm/fts5-slot@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/fts5-slot@0.1.0#describe")))
void __wasm_export_exports_sqlite_wasm_fts5_slot_describe_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
  if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
    free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
  }
  size_t len = *((size_t*) (arg0 + (5*sizeof(void*))));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + (4*sizeof(void*))));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr);
  }
  size_t len0 = *((size_t*) (arg0 + (7*sizeof(void*))));
  if (len0 > 0) {
    uint8_t *ptr1 = *((uint8_t **) (arg0 + (6*sizeof(void*))));
    for (size_t i2 = 0; i2 < len0; i2++) {
      uint8_t *base = ptr1 + i2 * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr1);
  }
  size_t len3 = *((size_t*) (arg0 + (9*sizeof(void*))));
  if (len3 > 0) {
    uint8_t *ptr4 = *((uint8_t **) (arg0 + (8*sizeof(void*))));
    for (size_t i5 = 0; i5 < len3; i5++) {
      uint8_t *base = ptr4 + i5 * (8+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr4);
  }
  size_t len6 = *((size_t*) (arg0 + (12*sizeof(void*))));
  if (len6 > 0) {
    uint8_t *ptr7 = *((uint8_t **) (arg0 + (11*sizeof(void*))));
    for (size_t i8 = 0; i8 < len6; i8++) {
      uint8_t *base = ptr7 + i8 * 1;
      (void) base;
    }
    free(ptr7);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/fts5-slot@0.1.0#call")))
void __wasm_export_exports_sqlite_wasm_fts5_slot_call_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 8))) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 4: {
          size_t len = *((size_t*) (arg0 + (16+1*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (arg0 + 16));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
          break;
        }
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + 8)));
      }
      break;
    }
  }
}

// Exported Functions from `sqlite:wasm/json1-slot@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/json1-slot@0.1.0#describe")))
void __wasm_export_exports_sqlite_wasm_json1_slot_describe_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
  if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
    free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
  }
  size_t len = *((size_t*) (arg0 + (5*sizeof(void*))));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + (4*sizeof(void*))));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr);
  }
  size_t len0 = *((size_t*) (arg0 + (7*sizeof(void*))));
  if (len0 > 0) {
    uint8_t *ptr1 = *((uint8_t **) (arg0 + (6*sizeof(void*))));
    for (size_t i2 = 0; i2 < len0; i2++) {
      uint8_t *base = ptr1 + i2 * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr1);
  }
  size_t len3 = *((size_t*) (arg0 + (9*sizeof(void*))));
  if (len3 > 0) {
    uint8_t *ptr4 = *((uint8_t **) (arg0 + (8*sizeof(void*))));
    for (size_t i5 = 0; i5 < len3; i5++) {
      uint8_t *base = ptr4 + i5 * (8+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr4);
  }
  size_t len6 = *((size_t*) (arg0 + (12*sizeof(void*))));
  if (len6 > 0) {
    uint8_t *ptr7 = *((uint8_t **) (arg0 + (11*sizeof(void*))));
    for (size_t i8 = 0; i8 < len6; i8++) {
      uint8_t *base = ptr7 + i8 * 1;
      (void) base;
    }
    free(ptr7);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/json1-slot@0.1.0#call")))
void __wasm_export_exports_sqlite_wasm_json1_slot_call_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 8))) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 4: {
          size_t len = *((size_t*) (arg0 + (16+1*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (arg0 + 16));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
          break;
        }
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + 8)));
      }
      break;
    }
  }
}

// Exported Functions from `sqlite:wasm/rtree-slot@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/rtree-slot@0.1.0#describe")))
void __wasm_export_exports_sqlite_wasm_rtree_slot_describe_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
  if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
    free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
  }
  size_t len = *((size_t*) (arg0 + (5*sizeof(void*))));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + (4*sizeof(void*))));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr);
  }
  size_t len0 = *((size_t*) (arg0 + (7*sizeof(void*))));
  if (len0 > 0) {
    uint8_t *ptr1 = *((uint8_t **) (arg0 + (6*sizeof(void*))));
    for (size_t i2 = 0; i2 < len0; i2++) {
      uint8_t *base = ptr1 + i2 * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr1);
  }
  size_t len3 = *((size_t*) (arg0 + (9*sizeof(void*))));
  if (len3 > 0) {
    uint8_t *ptr4 = *((uint8_t **) (arg0 + (8*sizeof(void*))));
    for (size_t i5 = 0; i5 < len3; i5++) {
      uint8_t *base = ptr4 + i5 * (8+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr4);
  }
  size_t len6 = *((size_t*) (arg0 + (12*sizeof(void*))));
  if (len6 > 0) {
    uint8_t *ptr7 = *((uint8_t **) (arg0 + (11*sizeof(void*))));
    for (size_t i8 = 0; i8 < len6; i8++) {
      uint8_t *base = ptr7 + i8 * 1;
      (void) base;
    }
    free(ptr7);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/rtree-slot@0.1.0#call")))
void __wasm_export_exports_sqlite_wasm_rtree_slot_call_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 8))) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 4: {
          size_t len = *((size_t*) (arg0 + (16+1*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (arg0 + 16));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
          break;
        }
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + 8)));
      }
      break;
    }
  }
}

// Exported Functions from `sqlite:wasm/geopoly-slot@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/geopoly-slot@0.1.0#describe")))
void __wasm_export_exports_sqlite_wasm_geopoly_slot_describe_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
  if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
    free(*((uint8_t **) (arg0 + (2*sizeof(void*)))));
  }
  size_t len = *((size_t*) (arg0 + (5*sizeof(void*))));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + (4*sizeof(void*))));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr);
  }
  size_t len0 = *((size_t*) (arg0 + (7*sizeof(void*))));
  if (len0 > 0) {
    uint8_t *ptr1 = *((uint8_t **) (arg0 + (6*sizeof(void*))));
    for (size_t i2 = 0; i2 < len0; i2++) {
      uint8_t *base = ptr1 + i2 * (16+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr1);
  }
  size_t len3 = *((size_t*) (arg0 + (9*sizeof(void*))));
  if (len3 > 0) {
    uint8_t *ptr4 = *((uint8_t **) (arg0 + (8*sizeof(void*))));
    for (size_t i5 = 0; i5 < len3; i5++) {
      uint8_t *base = ptr4 + i5 * (8+2*sizeof(void*));
      (void) base;
      if ((*((size_t*) (base + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (base + 8)));
      }
    }
    free(ptr4);
  }
  size_t len6 = *((size_t*) (arg0 + (12*sizeof(void*))));
  if (len6 > 0) {
    uint8_t *ptr7 = *((uint8_t **) (arg0 + (11*sizeof(void*))));
    for (size_t i8 = 0; i8 < len6; i8++) {
      uint8_t *base = ptr7 + i8 * 1;
      (void) base;
    }
    free(ptr7);
  }
}

__attribute__((__weak__, __export_name__("cabi_post_sqlite:wasm/geopoly-slot@0.1.0#call")))
void __wasm_export_exports_sqlite_wasm_geopoly_slot_call_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 8))) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          break;
        }
        case 3: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 4: {
          size_t len = *((size_t*) (arg0 + (16+1*sizeof(void*))));
          if (len > 0) {
            uint8_t *ptr = *((uint8_t **) (arg0 + 16));
            for (size_t i = 0; i < len; i++) {
              uint8_t *base = ptr + i * 1;
              (void) base;
            }
            free(ptr);
          }
          break;
        }
      }
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (8+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + 8)));
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(8)))
static uint8_t RET_AREA[(13*sizeof(void*))];

// Helper Functions

void demo_extension_list_u8_free(demo_extension_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void sqlite_extension_types_sql_value_free(sqlite_extension_types_sql_value_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 1: {
      break;
    }
    case 2: {
      break;
    }
    case 3: {
      demo_extension_string_free(&ptr->val.text);
      break;
    }
    case 4: {
      demo_extension_list_u8_free(&ptr->val.blob);
      break;
    }
  }
}

void sqlite_extension_types_sqlite_error_free(sqlite_extension_types_sqlite_error_t *ptr) {
  demo_extension_string_free(&ptr->message);
}

void demo_extension_option_string_free(demo_extension_option_string_t *ptr) {
  if (ptr->is_some) {
    demo_extension_string_free(&ptr->val);
  }
}

void sqlite_extension_types_column_info_free(sqlite_extension_types_column_info_t *ptr) {
  demo_extension_string_free(&ptr->name);
  demo_extension_option_string_free(&ptr->decl_type);
  demo_extension_option_string_free(&ptr->database);
  demo_extension_option_string_free(&ptr->table);
  demo_extension_option_string_free(&ptr->origin);
}

void sqlite_extension_types_list_column_info_free(sqlite_extension_types_list_column_info_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_types_column_info_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_types_column_info_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void demo_extension_list_string_free(demo_extension_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    demo_extension_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      demo_extension_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_types_table_info_free(sqlite_extension_types_table_info_t *ptr) {
  demo_extension_string_free(&ptr->name);
  sqlite_extension_types_list_column_info_free(&ptr->columns);
  demo_extension_list_string_free(&ptr->pk_columns);
}

void sqlite_extension_types_list_sql_value_free(sqlite_extension_types_list_sql_value_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_types_sql_value_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_types_sql_value_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_types_list_list_sql_value_free(sqlite_extension_types_list_list_sql_value_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_types_list_sql_value_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_types_list_sql_value_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_types_query_result_free(sqlite_extension_types_query_result_t *ptr) {
  demo_extension_list_string_free(&ptr->columns);
  sqlite_extension_types_list_list_sql_value_free(&ptr->rows);
}

void sqlite_extension_http_method_free(sqlite_extension_http_method_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 9: {
      demo_extension_string_free(&ptr->val.other);
      break;
    }
  }
}

void sqlite_extension_http_scheme_free(sqlite_extension_http_scheme_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 2: {
      demo_extension_string_free(&ptr->val.other);
      break;
    }
  }
}

void sqlite_extension_http_field_free(sqlite_extension_http_field_t *ptr) {
  demo_extension_string_free(&ptr->f0);
  demo_extension_list_u8_free(&ptr->f1);
}

void sqlite_extension_http_option_scheme_free(sqlite_extension_http_option_scheme_t *ptr) {
  if (ptr->is_some) {
    sqlite_extension_http_scheme_free(&ptr->val);
  }
}

void demo_extension_list_field_free(demo_extension_list_field_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_http_field_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_http_field_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void demo_extension_option_list_u8_free(demo_extension_option_list_u8_t *ptr) {
  if (ptr->is_some) {
    demo_extension_list_u8_free(&ptr->val);
  }
}

void demo_extension_option_u32_free(demo_extension_option_u32_t *ptr) {
  if (ptr->is_some) {
  }
}

void sqlite_extension_http_request_free(sqlite_extension_http_request_t *ptr) {
  sqlite_extension_http_method_free(&ptr->method);
  sqlite_extension_http_option_scheme_free(&ptr->scheme);
  demo_extension_option_string_free(&ptr->authority);
  demo_extension_option_string_free(&ptr->path_with_query);
  demo_extension_list_field_free(&ptr->headers);
  demo_extension_option_list_u8_free(&ptr->body);
  demo_extension_option_u32_free(&ptr->timeout_ms);
}

void sqlite_extension_http_response_free(sqlite_extension_http_response_t *ptr) {
  demo_extension_list_field_free(&ptr->headers);
  demo_extension_list_u8_free(&ptr->body);
}

void sqlite_extension_http_http_error_free(sqlite_extension_http_http_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      demo_extension_string_free(&ptr->val.invalid_url);
      break;
    }
    case 2: {
      demo_extension_string_free(&ptr->val.connection_error);
      break;
    }
    case 3: {
      demo_extension_string_free(&ptr->val.protocol_error);
      break;
    }
    case 4: {
      demo_extension_string_free(&ptr->val.other);
      break;
    }
  }
}

void sqlite_extension_http_result_response_http_error_free(sqlite_extension_http_result_response_http_error_t *ptr) {
  if (!ptr->is_err) {
    sqlite_extension_http_response_free(&ptr->val.ok);
  } else {
    sqlite_extension_http_http_error_free(&ptr->val.err);
  }
}

void sqlite_extension_policy_method_free(sqlite_extension_policy_method_t *ptr) {
  sqlite_extension_http_method_free(ptr);
}

void sqlite_extension_policy_capability_free(sqlite_extension_policy_capability_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void sqlite_extension_policy_list_method_free(sqlite_extension_policy_list_method_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_policy_method_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_policy_method_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_policy_option_list_method_free(sqlite_extension_policy_option_list_method_t *ptr) {
  if (ptr->is_some) {
    sqlite_extension_policy_list_method_free(&ptr->val);
  }
}

void demo_extension_option_u64_free(demo_extension_option_u64_t *ptr) {
  if (ptr->is_some) {
  }
}

void sqlite_extension_policy_http_policy_free(sqlite_extension_policy_http_policy_t *ptr) {
  demo_extension_list_string_free(&ptr->allowed_hosts);
  sqlite_extension_policy_option_list_method_free(&ptr->allowed_methods);
  demo_extension_option_u64_free(&ptr->max_body_bytes);
  demo_extension_option_u32_free(&ptr->timeout_ms);
}

void sqlite_extension_policy_fs_policy_free(sqlite_extension_policy_fs_policy_t *ptr) {
  demo_extension_list_string_free(&ptr->readable_prefixes);
  demo_extension_list_string_free(&ptr->writable_prefixes);
  demo_extension_option_u64_free(&ptr->max_write_bytes_per_call);
}

void sqlite_extension_policy_option_http_policy_free(sqlite_extension_policy_option_http_policy_t *ptr) {
  if (ptr->is_some) {
    sqlite_extension_policy_http_policy_free(&ptr->val);
  }
}

void sqlite_extension_policy_option_fs_policy_free(sqlite_extension_policy_option_fs_policy_t *ptr) {
  if (ptr->is_some) {
    sqlite_extension_policy_fs_policy_free(&ptr->val);
  }
}

void sqlite_extension_policy_list_capability_free(sqlite_extension_policy_list_capability_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_policy_capability_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_policy_capability_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_policy_load_options_free(sqlite_extension_policy_load_options_t *ptr) {
  demo_extension_option_u64_free(&ptr->fuel_per_call);
  demo_extension_option_u64_free(&ptr->memory_limit_bytes);
  demo_extension_option_u64_free(&ptr->epoch_deadline_ms);
  sqlite_extension_policy_option_http_policy_free(&ptr->http_policy);
  sqlite_extension_policy_option_fs_policy_free(&ptr->fs_policy);
  sqlite_extension_policy_list_capability_free(&ptr->grant);
}

void sqlite_extension_policy_policy_error_free(sqlite_extension_policy_policy_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      sqlite_extension_policy_capability_free(&ptr->val.capability_not_granted);
      break;
    }
    case 1: {
      sqlite_extension_policy_capability_free(&ptr->val.capability_not_declared);
      break;
    }
    case 2: {
      demo_extension_string_free(&ptr->val.host_not_allowed);
      break;
    }
    case 3: {
      sqlite_extension_policy_method_free(&ptr->val.method_not_allowed);
      break;
    }
  }
}

void sqlite_extension_metadata_capability_free(sqlite_extension_metadata_capability_t *ptr) {
  sqlite_extension_policy_capability_free(ptr);
}

void sqlite_extension_metadata_scalar_function_spec_free(sqlite_extension_metadata_scalar_function_spec_t *ptr) {
  demo_extension_string_free(&ptr->name);
}

void sqlite_extension_metadata_aggregate_function_spec_free(sqlite_extension_metadata_aggregate_function_spec_t *ptr) {
  demo_extension_string_free(&ptr->name);
}

void sqlite_extension_metadata_collation_spec_free(sqlite_extension_metadata_collation_spec_t *ptr) {
  demo_extension_string_free(&ptr->name);
}

void sqlite_extension_metadata_list_scalar_function_spec_free(sqlite_extension_metadata_list_scalar_function_spec_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_metadata_scalar_function_spec_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_metadata_scalar_function_spec_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_metadata_list_aggregate_function_spec_free(sqlite_extension_metadata_list_aggregate_function_spec_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_metadata_aggregate_function_spec_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_metadata_aggregate_function_spec_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_metadata_list_collation_spec_free(sqlite_extension_metadata_list_collation_spec_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_metadata_collation_spec_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_metadata_collation_spec_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_metadata_list_capability_free(sqlite_extension_metadata_list_capability_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    sqlite_extension_metadata_capability_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      sqlite_extension_metadata_capability_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void sqlite_extension_metadata_manifest_free(sqlite_extension_metadata_manifest_t *ptr) {
  demo_extension_string_free(&ptr->name);
  demo_extension_string_free(&ptr->version);
  sqlite_extension_metadata_list_scalar_function_spec_free(&ptr->scalar_functions);
  sqlite_extension_metadata_list_aggregate_function_spec_free(&ptr->aggregate_functions);
  sqlite_extension_metadata_list_collation_spec_free(&ptr->collations);
  sqlite_extension_metadata_list_capability_free(&ptr->declared_capabilities);
}

void exports_sqlite_wasm_demo_slot_sql_value_free(exports_sqlite_wasm_demo_slot_sql_value_t *ptr) {
  sqlite_extension_types_sql_value_free(ptr);
}

void exports_sqlite_wasm_demo_slot_manifest_free(exports_sqlite_wasm_demo_slot_manifest_t *ptr) {
  sqlite_extension_metadata_manifest_free(ptr);
}

void exports_sqlite_wasm_demo_slot_list_sql_value_free(exports_sqlite_wasm_demo_slot_list_sql_value_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_sqlite_wasm_demo_slot_sql_value_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_sqlite_wasm_demo_slot_sql_value_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_sqlite_wasm_demo_slot_result_sql_value_string_free(exports_sqlite_wasm_demo_slot_result_sql_value_string_t *ptr) {
  if (!ptr->is_err) {
    exports_sqlite_wasm_demo_slot_sql_value_free(&ptr->val.ok);
  } else {
    demo_extension_string_free(&ptr->val.err);
  }
}

void exports_sqlite_wasm_fts5_slot_sql_value_free(exports_sqlite_wasm_fts5_slot_sql_value_t *ptr) {
  sqlite_extension_types_sql_value_free(ptr);
}

void exports_sqlite_wasm_fts5_slot_manifest_free(exports_sqlite_wasm_fts5_slot_manifest_t *ptr) {
  sqlite_extension_metadata_manifest_free(ptr);
}

void exports_sqlite_wasm_fts5_slot_list_sql_value_free(exports_sqlite_wasm_fts5_slot_list_sql_value_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_sqlite_wasm_fts5_slot_sql_value_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_sqlite_wasm_fts5_slot_sql_value_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_sqlite_wasm_fts5_slot_result_sql_value_string_free(exports_sqlite_wasm_fts5_slot_result_sql_value_string_t *ptr) {
  if (!ptr->is_err) {
    exports_sqlite_wasm_fts5_slot_sql_value_free(&ptr->val.ok);
  } else {
    demo_extension_string_free(&ptr->val.err);
  }
}

void exports_sqlite_wasm_json1_slot_sql_value_free(exports_sqlite_wasm_json1_slot_sql_value_t *ptr) {
  sqlite_extension_types_sql_value_free(ptr);
}

void exports_sqlite_wasm_json1_slot_manifest_free(exports_sqlite_wasm_json1_slot_manifest_t *ptr) {
  sqlite_extension_metadata_manifest_free(ptr);
}

void exports_sqlite_wasm_json1_slot_list_sql_value_free(exports_sqlite_wasm_json1_slot_list_sql_value_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_sqlite_wasm_json1_slot_sql_value_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_sqlite_wasm_json1_slot_sql_value_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_sqlite_wasm_json1_slot_result_sql_value_string_free(exports_sqlite_wasm_json1_slot_result_sql_value_string_t *ptr) {
  if (!ptr->is_err) {
    exports_sqlite_wasm_json1_slot_sql_value_free(&ptr->val.ok);
  } else {
    demo_extension_string_free(&ptr->val.err);
  }
}

void exports_sqlite_wasm_rtree_slot_sql_value_free(exports_sqlite_wasm_rtree_slot_sql_value_t *ptr) {
  sqlite_extension_types_sql_value_free(ptr);
}

void exports_sqlite_wasm_rtree_slot_manifest_free(exports_sqlite_wasm_rtree_slot_manifest_t *ptr) {
  sqlite_extension_metadata_manifest_free(ptr);
}

void exports_sqlite_wasm_rtree_slot_list_sql_value_free(exports_sqlite_wasm_rtree_slot_list_sql_value_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_sqlite_wasm_rtree_slot_sql_value_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_sqlite_wasm_rtree_slot_sql_value_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_sqlite_wasm_rtree_slot_result_sql_value_string_free(exports_sqlite_wasm_rtree_slot_result_sql_value_string_t *ptr) {
  if (!ptr->is_err) {
    exports_sqlite_wasm_rtree_slot_sql_value_free(&ptr->val.ok);
  } else {
    demo_extension_string_free(&ptr->val.err);
  }
}

void exports_sqlite_wasm_geopoly_slot_sql_value_free(exports_sqlite_wasm_geopoly_slot_sql_value_t *ptr) {
  sqlite_extension_types_sql_value_free(ptr);
}

void exports_sqlite_wasm_geopoly_slot_manifest_free(exports_sqlite_wasm_geopoly_slot_manifest_t *ptr) {
  sqlite_extension_metadata_manifest_free(ptr);
}

void exports_sqlite_wasm_geopoly_slot_list_sql_value_free(exports_sqlite_wasm_geopoly_slot_list_sql_value_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_sqlite_wasm_geopoly_slot_sql_value_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_sqlite_wasm_geopoly_slot_sql_value_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_sqlite_wasm_geopoly_slot_result_sql_value_string_free(exports_sqlite_wasm_geopoly_slot_result_sql_value_string_t *ptr) {
  if (!ptr->is_err) {
    exports_sqlite_wasm_geopoly_slot_sql_value_free(&ptr->val.ok);
  } else {
    demo_extension_string_free(&ptr->val.err);
  }
}

void demo_extension_string_set(demo_extension_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void demo_extension_string_dup(demo_extension_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void demo_extension_string_free(demo_extension_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

bool sqlite_extension_http_handle(sqlite_extension_http_request_t *req, sqlite_extension_http_response_t *ret, sqlite_extension_http_http_error_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(8+18*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  switch ((int32_t) ((*req).method).tag) {
    case 0: {
      *((int8_t*)(ptr + 0)) = 0;
      break;
    }
    case 1: {
      *((int8_t*)(ptr + 0)) = 1;
      break;
    }
    case 2: {
      *((int8_t*)(ptr + 0)) = 2;
      break;
    }
    case 3: {
      *((int8_t*)(ptr + 0)) = 3;
      break;
    }
    case 4: {
      *((int8_t*)(ptr + 0)) = 4;
      break;
    }
    case 5: {
      *((int8_t*)(ptr + 0)) = 5;
      break;
    }
    case 6: {
      *((int8_t*)(ptr + 0)) = 6;
      break;
    }
    case 7: {
      *((int8_t*)(ptr + 0)) = 7;
      break;
    }
    case 8: {
      *((int8_t*)(ptr + 0)) = 8;
      break;
    }
    case 9: {
      const demo_extension_string_t *payload8 = &((*req).method).val.other;
      *((int8_t*)(ptr + 0)) = 9;
      *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload8).len;
      *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload8).ptr;
      break;
    }
  }
  if (((*req).scheme).is_some) {
    const sqlite_extension_http_scheme_t *payload10 = &((*req).scheme).val;
    *((int8_t*)(ptr + (3*sizeof(void*)))) = 1;
    switch ((int32_t) (*payload10).tag) {
      case 0: {
        *((int8_t*)(ptr + (4*sizeof(void*)))) = 0;
        break;
      }
      case 1: {
        *((int8_t*)(ptr + (4*sizeof(void*)))) = 1;
        break;
      }
      case 2: {
        const demo_extension_string_t *payload13 = &(*payload10).val.other;
        *((int8_t*)(ptr + (4*sizeof(void*)))) = 2;
        *((size_t*)(ptr + (6*sizeof(void*)))) = (*payload13).len;
        *((uint8_t **)(ptr + (5*sizeof(void*)))) = (uint8_t *) (*payload13).ptr;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + (3*sizeof(void*)))) = 0;
  }
  if (((*req).authority).is_some) {
    const demo_extension_string_t *payload15 = &((*req).authority).val;
    *((int8_t*)(ptr + (7*sizeof(void*)))) = 1;
    *((size_t*)(ptr + (9*sizeof(void*)))) = (*payload15).len;
    *((uint8_t **)(ptr + (8*sizeof(void*)))) = (uint8_t *) (*payload15).ptr;
  } else {
    *((int8_t*)(ptr + (7*sizeof(void*)))) = 0;
  }
  if (((*req).path_with_query).is_some) {
    const demo_extension_string_t *payload17 = &((*req).path_with_query).val;
    *((int8_t*)(ptr + (10*sizeof(void*)))) = 1;
    *((size_t*)(ptr + (12*sizeof(void*)))) = (*payload17).len;
    *((uint8_t **)(ptr + (11*sizeof(void*)))) = (uint8_t *) (*payload17).ptr;
  } else {
    *((int8_t*)(ptr + (10*sizeof(void*)))) = 0;
  }
  *((size_t*)(ptr + (14*sizeof(void*)))) = ((*req).headers).len;
  *((uint8_t **)(ptr + (13*sizeof(void*)))) = (uint8_t *) ((*req).headers).ptr;
  if (((*req).body).is_some) {
    const demo_extension_list_u8_t *payload19 = &((*req).body).val;
    *((int8_t*)(ptr + (15*sizeof(void*)))) = 1;
    *((size_t*)(ptr + (17*sizeof(void*)))) = (*payload19).len;
    *((uint8_t **)(ptr + (16*sizeof(void*)))) = (uint8_t *) (*payload19).ptr;
  } else {
    *((int8_t*)(ptr + (15*sizeof(void*)))) = 0;
  }
  if (((*req).timeout_ms).is_some) {
    const uint32_t *payload21 = &((*req).timeout_ms).val;
    *((int8_t*)(ptr + (18*sizeof(void*)))) = 1;
    *((int32_t*)(ptr + (4+18*sizeof(void*)))) = (int32_t) (*payload21);
  } else {
    *((int8_t*)(ptr + (18*sizeof(void*)))) = 0;
  }
  uint8_t *ptr22 = (uint8_t *) &ret_area;
  __wasm_import_sqlite_extension_http_handle(ptr, ptr22);
  sqlite_extension_http_result_response_http_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr22 + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (sqlite_extension_http_response_t) {
        (uint16_t) (uint16_t) ((int32_t) *((uint16_t*) (ptr22 + sizeof(void*)))),
        (demo_extension_list_field_t) (demo_extension_list_field_t) { (sqlite_extension_http_field_t*)(*((uint8_t **) (ptr22 + (2*sizeof(void*))))), (*((size_t*) (ptr22 + (3*sizeof(void*))))) },
        (demo_extension_list_u8_t) (demo_extension_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr22 + (4*sizeof(void*))))), (*((size_t*) (ptr22 + (5*sizeof(void*))))) },
      };
      break;
    }
    case 1: {
      result.is_err = true;
      sqlite_extension_http_http_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr22 + sizeof(void*)));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.invalid_url = (demo_extension_string_t) { (uint8_t*)(*((uint8_t **) (ptr22 + (2*sizeof(void*))))), (*((size_t*) (ptr22 + (3*sizeof(void*))))) };
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          variant.val.connection_error = (demo_extension_string_t) { (uint8_t*)(*((uint8_t **) (ptr22 + (2*sizeof(void*))))), (*((size_t*) (ptr22 + (3*sizeof(void*))))) };
          break;
        }
        case 3: {
          variant.val.protocol_error = (demo_extension_string_t) { (uint8_t*)(*((uint8_t **) (ptr22 + (2*sizeof(void*))))), (*((size_t*) (ptr22 + (3*sizeof(void*))))) };
          break;
        }
        case 4: {
          variant.val.other = (demo_extension_string_t) { (uint8_t*)(*((uint8_t **) (ptr22 + (2*sizeof(void*))))), (*((size_t*) (ptr22 + (3*sizeof(void*))))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

void sqlite_extension_metadata_describe(sqlite_extension_metadata_manifest_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(13*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_sqlite_extension_metadata_describe(ptr);
  *ret = (sqlite_extension_metadata_manifest_t) {
    (demo_extension_string_t) (demo_extension_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) },
    (demo_extension_string_t) (demo_extension_string_t) { (uint8_t*)(*((uint8_t **) (ptr + (2*sizeof(void*))))), (*((size_t*) (ptr + (3*sizeof(void*))))) },
    (sqlite_extension_metadata_list_scalar_function_spec_t) (sqlite_extension_metadata_list_scalar_function_spec_t) { (sqlite_extension_metadata_scalar_function_spec_t*)(*((uint8_t **) (ptr + (4*sizeof(void*))))), (*((size_t*) (ptr + (5*sizeof(void*))))) },
    (sqlite_extension_metadata_list_aggregate_function_spec_t) (sqlite_extension_metadata_list_aggregate_function_spec_t) { (sqlite_extension_metadata_aggregate_function_spec_t*)(*((uint8_t **) (ptr + (6*sizeof(void*))))), (*((size_t*) (ptr + (7*sizeof(void*))))) },
    (sqlite_extension_metadata_list_collation_spec_t) (sqlite_extension_metadata_list_collation_spec_t) { (sqlite_extension_metadata_collation_spec_t*)(*((uint8_t **) (ptr + (8*sizeof(void*))))), (*((size_t*) (ptr + (9*sizeof(void*))))) },
    (bool) (int32_t) *((uint8_t*) (ptr + (10*sizeof(void*)))),
    (bool) (int32_t) *((uint8_t*) (ptr + (1+10*sizeof(void*)))),
    (bool) (int32_t) *((uint8_t*) (ptr + (2+10*sizeof(void*)))),
    (sqlite_extension_metadata_list_capability_t) (sqlite_extension_metadata_list_capability_t) { (sqlite_extension_metadata_capability_t*)(*((uint8_t **) (ptr + (11*sizeof(void*))))), (*((size_t*) (ptr + (12*sizeof(void*))))) },
  };
}

__attribute__((__export_name__("sqlite:wasm/demo-slot@0.1.0#describe")))
uint8_t * __wasm_export_exports_sqlite_wasm_demo_slot_describe(void) {
  exports_sqlite_wasm_demo_slot_manifest_t ret;
  exports_sqlite_wasm_demo_slot_describe(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = ((ret).name).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).name).ptr;
  *((size_t*)(ptr + (3*sizeof(void*)))) = ((ret).version).len;
  *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) ((ret).version).ptr;
  *((size_t*)(ptr + (5*sizeof(void*)))) = ((ret).scalar_functions).len;
  *((uint8_t **)(ptr + (4*sizeof(void*)))) = (uint8_t *) ((ret).scalar_functions).ptr;
  *((size_t*)(ptr + (7*sizeof(void*)))) = ((ret).aggregate_functions).len;
  *((uint8_t **)(ptr + (6*sizeof(void*)))) = (uint8_t *) ((ret).aggregate_functions).ptr;
  *((size_t*)(ptr + (9*sizeof(void*)))) = ((ret).collations).len;
  *((uint8_t **)(ptr + (8*sizeof(void*)))) = (uint8_t *) ((ret).collations).ptr;
  *((int8_t*)(ptr + (10*sizeof(void*)))) = (ret).has_authorizer;
  *((int8_t*)(ptr + (1+10*sizeof(void*)))) = (ret).has_update_hook;
  *((int8_t*)(ptr + (2+10*sizeof(void*)))) = (ret).has_commit_hook;
  *((size_t*)(ptr + (12*sizeof(void*)))) = ((ret).declared_capabilities).len;
  *((uint8_t **)(ptr + (11*sizeof(void*)))) = (uint8_t *) ((ret).declared_capabilities).ptr;
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/demo-slot@0.1.0#call")))
uint8_t * __wasm_export_exports_sqlite_wasm_demo_slot_call(int64_t arg, uint8_t * arg0, size_t arg1) {
  exports_sqlite_wasm_demo_slot_list_sql_value_t arg2 = (exports_sqlite_wasm_demo_slot_list_sql_value_t) { (exports_sqlite_wasm_demo_slot_sql_value_t*)(arg0), (arg1) };
  exports_sqlite_wasm_demo_slot_result_sql_value_string_t ret;
  exports_sqlite_wasm_demo_slot_sql_value_t ok;
  demo_extension_string_t err;
  ret.is_err = !exports_sqlite_wasm_demo_slot_call((uint64_t) (arg), &arg2, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const demo_extension_string_t *payload8 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (8+1*sizeof(void*)))) = (*payload8).len;
    *((uint8_t **)(ptr + 8)) = (uint8_t *) (*payload8).ptr;
  } else {
    const exports_sqlite_wasm_demo_slot_sql_value_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    switch ((int32_t) (*payload).tag) {
      case 0: {
        *((int8_t*)(ptr + 8)) = 0;
        break;
      }
      case 1: {
        const int64_t *payload4 = &(*payload).val.integer;
        *((int8_t*)(ptr + 8)) = 1;
        *((int64_t*)(ptr + 16)) = *payload4;
        break;
      }
      case 2: {
        const double *payload5 = &(*payload).val.real;
        *((int8_t*)(ptr + 8)) = 2;
        *((double*)(ptr + 16)) = *payload5;
        break;
      }
      case 3: {
        const demo_extension_string_t *payload6 = &(*payload).val.text;
        *((int8_t*)(ptr + 8)) = 3;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload6).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload6).ptr;
        break;
      }
      case 4: {
        const demo_extension_list_u8_t *payload7 = &(*payload).val.blob;
        *((int8_t*)(ptr + 8)) = 4;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload7).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload7).ptr;
        break;
      }
    }
  }
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/fts5-slot@0.1.0#describe")))
uint8_t * __wasm_export_exports_sqlite_wasm_fts5_slot_describe(void) {
  exports_sqlite_wasm_fts5_slot_manifest_t ret;
  exports_sqlite_wasm_fts5_slot_describe(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = ((ret).name).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).name).ptr;
  *((size_t*)(ptr + (3*sizeof(void*)))) = ((ret).version).len;
  *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) ((ret).version).ptr;
  *((size_t*)(ptr + (5*sizeof(void*)))) = ((ret).scalar_functions).len;
  *((uint8_t **)(ptr + (4*sizeof(void*)))) = (uint8_t *) ((ret).scalar_functions).ptr;
  *((size_t*)(ptr + (7*sizeof(void*)))) = ((ret).aggregate_functions).len;
  *((uint8_t **)(ptr + (6*sizeof(void*)))) = (uint8_t *) ((ret).aggregate_functions).ptr;
  *((size_t*)(ptr + (9*sizeof(void*)))) = ((ret).collations).len;
  *((uint8_t **)(ptr + (8*sizeof(void*)))) = (uint8_t *) ((ret).collations).ptr;
  *((int8_t*)(ptr + (10*sizeof(void*)))) = (ret).has_authorizer;
  *((int8_t*)(ptr + (1+10*sizeof(void*)))) = (ret).has_update_hook;
  *((int8_t*)(ptr + (2+10*sizeof(void*)))) = (ret).has_commit_hook;
  *((size_t*)(ptr + (12*sizeof(void*)))) = ((ret).declared_capabilities).len;
  *((uint8_t **)(ptr + (11*sizeof(void*)))) = (uint8_t *) ((ret).declared_capabilities).ptr;
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/fts5-slot@0.1.0#call")))
uint8_t * __wasm_export_exports_sqlite_wasm_fts5_slot_call(int64_t arg, uint8_t * arg0, size_t arg1) {
  exports_sqlite_wasm_fts5_slot_list_sql_value_t arg2 = (exports_sqlite_wasm_fts5_slot_list_sql_value_t) { (exports_sqlite_wasm_fts5_slot_sql_value_t*)(arg0), (arg1) };
  exports_sqlite_wasm_fts5_slot_result_sql_value_string_t ret;
  exports_sqlite_wasm_fts5_slot_sql_value_t ok;
  demo_extension_string_t err;
  ret.is_err = !exports_sqlite_wasm_fts5_slot_call((uint64_t) (arg), &arg2, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const demo_extension_string_t *payload8 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (8+1*sizeof(void*)))) = (*payload8).len;
    *((uint8_t **)(ptr + 8)) = (uint8_t *) (*payload8).ptr;
  } else {
    const exports_sqlite_wasm_fts5_slot_sql_value_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    switch ((int32_t) (*payload).tag) {
      case 0: {
        *((int8_t*)(ptr + 8)) = 0;
        break;
      }
      case 1: {
        const int64_t *payload4 = &(*payload).val.integer;
        *((int8_t*)(ptr + 8)) = 1;
        *((int64_t*)(ptr + 16)) = *payload4;
        break;
      }
      case 2: {
        const double *payload5 = &(*payload).val.real;
        *((int8_t*)(ptr + 8)) = 2;
        *((double*)(ptr + 16)) = *payload5;
        break;
      }
      case 3: {
        const demo_extension_string_t *payload6 = &(*payload).val.text;
        *((int8_t*)(ptr + 8)) = 3;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload6).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload6).ptr;
        break;
      }
      case 4: {
        const demo_extension_list_u8_t *payload7 = &(*payload).val.blob;
        *((int8_t*)(ptr + 8)) = 4;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload7).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload7).ptr;
        break;
      }
    }
  }
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/json1-slot@0.1.0#describe")))
uint8_t * __wasm_export_exports_sqlite_wasm_json1_slot_describe(void) {
  exports_sqlite_wasm_json1_slot_manifest_t ret;
  exports_sqlite_wasm_json1_slot_describe(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = ((ret).name).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).name).ptr;
  *((size_t*)(ptr + (3*sizeof(void*)))) = ((ret).version).len;
  *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) ((ret).version).ptr;
  *((size_t*)(ptr + (5*sizeof(void*)))) = ((ret).scalar_functions).len;
  *((uint8_t **)(ptr + (4*sizeof(void*)))) = (uint8_t *) ((ret).scalar_functions).ptr;
  *((size_t*)(ptr + (7*sizeof(void*)))) = ((ret).aggregate_functions).len;
  *((uint8_t **)(ptr + (6*sizeof(void*)))) = (uint8_t *) ((ret).aggregate_functions).ptr;
  *((size_t*)(ptr + (9*sizeof(void*)))) = ((ret).collations).len;
  *((uint8_t **)(ptr + (8*sizeof(void*)))) = (uint8_t *) ((ret).collations).ptr;
  *((int8_t*)(ptr + (10*sizeof(void*)))) = (ret).has_authorizer;
  *((int8_t*)(ptr + (1+10*sizeof(void*)))) = (ret).has_update_hook;
  *((int8_t*)(ptr + (2+10*sizeof(void*)))) = (ret).has_commit_hook;
  *((size_t*)(ptr + (12*sizeof(void*)))) = ((ret).declared_capabilities).len;
  *((uint8_t **)(ptr + (11*sizeof(void*)))) = (uint8_t *) ((ret).declared_capabilities).ptr;
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/json1-slot@0.1.0#call")))
uint8_t * __wasm_export_exports_sqlite_wasm_json1_slot_call(int64_t arg, uint8_t * arg0, size_t arg1) {
  exports_sqlite_wasm_json1_slot_list_sql_value_t arg2 = (exports_sqlite_wasm_json1_slot_list_sql_value_t) { (exports_sqlite_wasm_json1_slot_sql_value_t*)(arg0), (arg1) };
  exports_sqlite_wasm_json1_slot_result_sql_value_string_t ret;
  exports_sqlite_wasm_json1_slot_sql_value_t ok;
  demo_extension_string_t err;
  ret.is_err = !exports_sqlite_wasm_json1_slot_call((uint64_t) (arg), &arg2, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const demo_extension_string_t *payload8 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (8+1*sizeof(void*)))) = (*payload8).len;
    *((uint8_t **)(ptr + 8)) = (uint8_t *) (*payload8).ptr;
  } else {
    const exports_sqlite_wasm_json1_slot_sql_value_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    switch ((int32_t) (*payload).tag) {
      case 0: {
        *((int8_t*)(ptr + 8)) = 0;
        break;
      }
      case 1: {
        const int64_t *payload4 = &(*payload).val.integer;
        *((int8_t*)(ptr + 8)) = 1;
        *((int64_t*)(ptr + 16)) = *payload4;
        break;
      }
      case 2: {
        const double *payload5 = &(*payload).val.real;
        *((int8_t*)(ptr + 8)) = 2;
        *((double*)(ptr + 16)) = *payload5;
        break;
      }
      case 3: {
        const demo_extension_string_t *payload6 = &(*payload).val.text;
        *((int8_t*)(ptr + 8)) = 3;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload6).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload6).ptr;
        break;
      }
      case 4: {
        const demo_extension_list_u8_t *payload7 = &(*payload).val.blob;
        *((int8_t*)(ptr + 8)) = 4;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload7).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload7).ptr;
        break;
      }
    }
  }
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/rtree-slot@0.1.0#describe")))
uint8_t * __wasm_export_exports_sqlite_wasm_rtree_slot_describe(void) {
  exports_sqlite_wasm_rtree_slot_manifest_t ret;
  exports_sqlite_wasm_rtree_slot_describe(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = ((ret).name).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).name).ptr;
  *((size_t*)(ptr + (3*sizeof(void*)))) = ((ret).version).len;
  *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) ((ret).version).ptr;
  *((size_t*)(ptr + (5*sizeof(void*)))) = ((ret).scalar_functions).len;
  *((uint8_t **)(ptr + (4*sizeof(void*)))) = (uint8_t *) ((ret).scalar_functions).ptr;
  *((size_t*)(ptr + (7*sizeof(void*)))) = ((ret).aggregate_functions).len;
  *((uint8_t **)(ptr + (6*sizeof(void*)))) = (uint8_t *) ((ret).aggregate_functions).ptr;
  *((size_t*)(ptr + (9*sizeof(void*)))) = ((ret).collations).len;
  *((uint8_t **)(ptr + (8*sizeof(void*)))) = (uint8_t *) ((ret).collations).ptr;
  *((int8_t*)(ptr + (10*sizeof(void*)))) = (ret).has_authorizer;
  *((int8_t*)(ptr + (1+10*sizeof(void*)))) = (ret).has_update_hook;
  *((int8_t*)(ptr + (2+10*sizeof(void*)))) = (ret).has_commit_hook;
  *((size_t*)(ptr + (12*sizeof(void*)))) = ((ret).declared_capabilities).len;
  *((uint8_t **)(ptr + (11*sizeof(void*)))) = (uint8_t *) ((ret).declared_capabilities).ptr;
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/rtree-slot@0.1.0#call")))
uint8_t * __wasm_export_exports_sqlite_wasm_rtree_slot_call(int64_t arg, uint8_t * arg0, size_t arg1) {
  exports_sqlite_wasm_rtree_slot_list_sql_value_t arg2 = (exports_sqlite_wasm_rtree_slot_list_sql_value_t) { (exports_sqlite_wasm_rtree_slot_sql_value_t*)(arg0), (arg1) };
  exports_sqlite_wasm_rtree_slot_result_sql_value_string_t ret;
  exports_sqlite_wasm_rtree_slot_sql_value_t ok;
  demo_extension_string_t err;
  ret.is_err = !exports_sqlite_wasm_rtree_slot_call((uint64_t) (arg), &arg2, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const demo_extension_string_t *payload8 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (8+1*sizeof(void*)))) = (*payload8).len;
    *((uint8_t **)(ptr + 8)) = (uint8_t *) (*payload8).ptr;
  } else {
    const exports_sqlite_wasm_rtree_slot_sql_value_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    switch ((int32_t) (*payload).tag) {
      case 0: {
        *((int8_t*)(ptr + 8)) = 0;
        break;
      }
      case 1: {
        const int64_t *payload4 = &(*payload).val.integer;
        *((int8_t*)(ptr + 8)) = 1;
        *((int64_t*)(ptr + 16)) = *payload4;
        break;
      }
      case 2: {
        const double *payload5 = &(*payload).val.real;
        *((int8_t*)(ptr + 8)) = 2;
        *((double*)(ptr + 16)) = *payload5;
        break;
      }
      case 3: {
        const demo_extension_string_t *payload6 = &(*payload).val.text;
        *((int8_t*)(ptr + 8)) = 3;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload6).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload6).ptr;
        break;
      }
      case 4: {
        const demo_extension_list_u8_t *payload7 = &(*payload).val.blob;
        *((int8_t*)(ptr + 8)) = 4;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload7).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload7).ptr;
        break;
      }
    }
  }
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/geopoly-slot@0.1.0#describe")))
uint8_t * __wasm_export_exports_sqlite_wasm_geopoly_slot_describe(void) {
  exports_sqlite_wasm_geopoly_slot_manifest_t ret;
  exports_sqlite_wasm_geopoly_slot_describe(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = ((ret).name).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).name).ptr;
  *((size_t*)(ptr + (3*sizeof(void*)))) = ((ret).version).len;
  *((uint8_t **)(ptr + (2*sizeof(void*)))) = (uint8_t *) ((ret).version).ptr;
  *((size_t*)(ptr + (5*sizeof(void*)))) = ((ret).scalar_functions).len;
  *((uint8_t **)(ptr + (4*sizeof(void*)))) = (uint8_t *) ((ret).scalar_functions).ptr;
  *((size_t*)(ptr + (7*sizeof(void*)))) = ((ret).aggregate_functions).len;
  *((uint8_t **)(ptr + (6*sizeof(void*)))) = (uint8_t *) ((ret).aggregate_functions).ptr;
  *((size_t*)(ptr + (9*sizeof(void*)))) = ((ret).collations).len;
  *((uint8_t **)(ptr + (8*sizeof(void*)))) = (uint8_t *) ((ret).collations).ptr;
  *((int8_t*)(ptr + (10*sizeof(void*)))) = (ret).has_authorizer;
  *((int8_t*)(ptr + (1+10*sizeof(void*)))) = (ret).has_update_hook;
  *((int8_t*)(ptr + (2+10*sizeof(void*)))) = (ret).has_commit_hook;
  *((size_t*)(ptr + (12*sizeof(void*)))) = ((ret).declared_capabilities).len;
  *((uint8_t **)(ptr + (11*sizeof(void*)))) = (uint8_t *) ((ret).declared_capabilities).ptr;
  return ptr;
}

__attribute__((__export_name__("sqlite:wasm/geopoly-slot@0.1.0#call")))
uint8_t * __wasm_export_exports_sqlite_wasm_geopoly_slot_call(int64_t arg, uint8_t * arg0, size_t arg1) {
  exports_sqlite_wasm_geopoly_slot_list_sql_value_t arg2 = (exports_sqlite_wasm_geopoly_slot_list_sql_value_t) { (exports_sqlite_wasm_geopoly_slot_sql_value_t*)(arg0), (arg1) };
  exports_sqlite_wasm_geopoly_slot_result_sql_value_string_t ret;
  exports_sqlite_wasm_geopoly_slot_sql_value_t ok;
  demo_extension_string_t err;
  ret.is_err = !exports_sqlite_wasm_geopoly_slot_call((uint64_t) (arg), &arg2, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const demo_extension_string_t *payload8 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (8+1*sizeof(void*)))) = (*payload8).len;
    *((uint8_t **)(ptr + 8)) = (uint8_t *) (*payload8).ptr;
  } else {
    const exports_sqlite_wasm_geopoly_slot_sql_value_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    switch ((int32_t) (*payload).tag) {
      case 0: {
        *((int8_t*)(ptr + 8)) = 0;
        break;
      }
      case 1: {
        const int64_t *payload4 = &(*payload).val.integer;
        *((int8_t*)(ptr + 8)) = 1;
        *((int64_t*)(ptr + 16)) = *payload4;
        break;
      }
      case 2: {
        const double *payload5 = &(*payload).val.real;
        *((int8_t*)(ptr + 8)) = 2;
        *((double*)(ptr + 16)) = *payload5;
        break;
      }
      case 3: {
        const demo_extension_string_t *payload6 = &(*payload).val.text;
        *((int8_t*)(ptr + 8)) = 3;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload6).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload6).ptr;
        break;
      }
      case 4: {
        const demo_extension_list_u8_t *payload7 = &(*payload).val.blob;
        *((int8_t*)(ptr + 8)) = 4;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = (*payload7).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) (*payload7).ptr;
        break;
      }
    }
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_demo_extension(void);
__attribute__((used))
void __component_type_object_force_link_demo_extension_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_demo_extension();
}
