/**
 * Register text extension functions
 * Generated by build-extension.py
 */

import * as callbacks from './extension-callbacks.js';

/**
 * Register all text functions with a database handle
 * @param {bigint} db - Database handle from lowLevel.open()
 * @param {object} extension - Extension API from sqlite-extensible
 */
export function registerText(db, extension) {
    const handles = [];

    // Register sqlean_version
    handles.push(extension.registerScalarFunction(
        db, 'sqlean_version', 0,
        { deterministic: false },
        callbacks.FUNC_SQLEAN_VERSION
    ));

    // Register text_substring
    handles.push(extension.registerScalarFunction(
        db, 'text_substring', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_SUBSTRING
    ));

    // Register text_slice
    handles.push(extension.registerScalarFunction(
        db, 'text_slice', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_SLICE
    ));

    // Register text_left
    handles.push(extension.registerScalarFunction(
        db, 'text_left', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_LEFT
    ));

    // Register left
    handles.push(extension.registerScalarFunction(
        db, 'left', 2,
        { deterministic: false },
        callbacks.FUNC_LEFT
    ));

    // Register text_right
    handles.push(extension.registerScalarFunction(
        db, 'text_right', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_RIGHT
    ));

    // Register right
    handles.push(extension.registerScalarFunction(
        db, 'right', 2,
        { deterministic: false },
        callbacks.FUNC_RIGHT
    ));

    // Register text_index
    handles.push(extension.registerScalarFunction(
        db, 'text_index', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_INDEX
    ));

    // Register strpos
    handles.push(extension.registerScalarFunction(
        db, 'strpos', 2,
        { deterministic: false },
        callbacks.FUNC_STRPOS
    ));

    // Register text_last_index
    handles.push(extension.registerScalarFunction(
        db, 'text_last_index', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_LAST_INDEX
    ));

    // Register text_contains
    handles.push(extension.registerScalarFunction(
        db, 'text_contains', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_CONTAINS
    ));

    // Register text_has_prefix
    handles.push(extension.registerScalarFunction(
        db, 'text_has_prefix', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_HAS_PREFIX
    ));

    // Register starts_with
    handles.push(extension.registerScalarFunction(
        db, 'starts_with', 2,
        { deterministic: false },
        callbacks.FUNC_STARTS_WITH
    ));

    // Register text_has_suffix
    handles.push(extension.registerScalarFunction(
        db, 'text_has_suffix', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_HAS_SUFFIX
    ));

    // Register text_count
    handles.push(extension.registerScalarFunction(
        db, 'text_count', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_COUNT
    ));

    // Register text_like
    handles.push(extension.registerScalarFunction(
        db, 'text_like', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_LIKE
    ));

    // Register text_split
    handles.push(extension.registerScalarFunction(
        db, 'text_split', 3,
        { deterministic: false },
        callbacks.FUNC_TEXT_SPLIT
    ));

    // Register split_part
    handles.push(extension.registerScalarFunction(
        db, 'split_part', 3,
        { deterministic: false },
        callbacks.FUNC_SPLIT_PART
    ));

    // Register text_join
    handles.push(extension.registerScalarFunction(
        db, 'text_join', -1,
        { deterministic: false },
        callbacks.FUNC_TEXT_JOIN
    ));

    // Register concat_ws
    handles.push(extension.registerScalarFunction(
        db, 'concat_ws', -1,
        { deterministic: false },
        callbacks.FUNC_CONCAT_WS
    ));

    // Register text_concat
    handles.push(extension.registerScalarFunction(
        db, 'text_concat', -1,
        { deterministic: false },
        callbacks.FUNC_TEXT_CONCAT
    ));

    // Register concat
    handles.push(extension.registerScalarFunction(
        db, 'concat', -1,
        { deterministic: false },
        callbacks.FUNC_CONCAT
    ));

    // Register text_repeat
    handles.push(extension.registerScalarFunction(
        db, 'text_repeat', 2,
        { deterministic: false },
        callbacks.FUNC_TEXT_REPEAT
    ));

    // Register repeat
    handles.push(extension.registerScalarFunction(
        db, 'repeat', 2,
        { deterministic: false },
        callbacks.FUNC_REPEAT
    ));

    // Register text_ltrim
    handles.push(extension.registerScalarFunction(
        db, 'text_ltrim', -1,
        { deterministic: false },
        callbacks.FUNC_TEXT_LTRIM
    ));

    // Register ltrim
    handles.push(extension.registerScalarFunction(
        db, 'ltrim', -1,
        { deterministic: false },
        callbacks.FUNC_LTRIM
    ));

    // Register text_rtrim
    handles.push(extension.registerScalarFunction(
        db, 'text_rtrim', -1,
        { deterministic: false },
        callbacks.FUNC_TEXT_RTRIM
    ));

    // Register rtrim
    handles.push(extension.registerScalarFunction(
        db, 'rtrim', -1,
        { deterministic: false },
        callbacks.FUNC_RTRIM
    ));

    // Register text_trim
    handles.push(extension.registerScalarFunction(
        db, 'text_trim', -1,
        { deterministic: false },
        callbacks.FUNC_TEXT_TRIM
    ));

    // Register btrim
    handles.push(extension.registerScalarFunction(
        db, 'btrim', -1,
        { deterministic: false },
        callbacks.FUNC_BTRIM
    ));

    // Register text_lpad
    handles.push(extension.registerScalarFunction(
        db, 'text_lpad', -1,
        { deterministic: false },
        callbacks.FUNC_TEXT_LPAD
    ));

    // Register lpad
    handles.push(extension.registerScalarFunction(
        db, 'lpad', -1,
        { deterministic: false },
        callbacks.FUNC_LPAD
    ));

    // Register text_rpad
    handles.push(extension.registerScalarFunction(
        db, 'text_rpad', -1,
        { deterministic: false },
        callbacks.FUNC_TEXT_RPAD
    ));

    // Register rpad
    handles.push(extension.registerScalarFunction(
        db, 'rpad', -1,
        { deterministic: false },
        callbacks.FUNC_RPAD
    ));

    // Register text_upper
    handles.push(extension.registerScalarFunction(
        db, 'text_upper', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_UPPER
    ));

    // Register text_lower
    handles.push(extension.registerScalarFunction(
        db, 'text_lower', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_LOWER
    ));

    // Register text_title
    handles.push(extension.registerScalarFunction(
        db, 'text_title', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_TITLE
    ));

    // Register text_casefold
    handles.push(extension.registerScalarFunction(
        db, 'text_casefold', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_CASEFOLD
    ));

    // Register text_replace
    handles.push(extension.registerScalarFunction(
        db, 'text_replace', 3,
        { deterministic: false },
        callbacks.FUNC_TEXT_REPLACE
    ));

    // Register text_translate
    handles.push(extension.registerScalarFunction(
        db, 'text_translate', 3,
        { deterministic: false },
        callbacks.FUNC_TEXT_TRANSLATE
    ));

    // Register translate
    handles.push(extension.registerScalarFunction(
        db, 'translate', 3,
        { deterministic: false },
        callbacks.FUNC_TRANSLATE
    ));

    // Register text_reverse
    handles.push(extension.registerScalarFunction(
        db, 'text_reverse', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_REVERSE
    ));

    // Register reverse
    handles.push(extension.registerScalarFunction(
        db, 'reverse', 1,
        { deterministic: false },
        callbacks.FUNC_REVERSE
    ));

    // Register text_length
    handles.push(extension.registerScalarFunction(
        db, 'text_length', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_LENGTH
    ));

    // Register char_length
    handles.push(extension.registerScalarFunction(
        db, 'char_length', 1,
        { deterministic: false },
        callbacks.FUNC_CHAR_LENGTH
    ));

    // Register character_length
    handles.push(extension.registerScalarFunction(
        db, 'character_length', 1,
        { deterministic: false },
        callbacks.FUNC_CHARACTER_LENGTH
    ));

    // Register text_size
    handles.push(extension.registerScalarFunction(
        db, 'text_size', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_SIZE
    ));

    // Register octet_length
    handles.push(extension.registerScalarFunction(
        db, 'octet_length', 1,
        { deterministic: false },
        callbacks.FUNC_OCTET_LENGTH
    ));

    // Register text_bitsize
    handles.push(extension.registerScalarFunction(
        db, 'text_bitsize', 1,
        { deterministic: false },
        callbacks.FUNC_TEXT_BITSIZE
    ));

    // Register bit_length
    handles.push(extension.registerScalarFunction(
        db, 'bit_length', 1,
        { deterministic: false },
        callbacks.FUNC_BIT_LENGTH
    ));

    return handles;
}

export const FUNCTION_IDS = {
    sqlean_version: callbacks.FUNC_SQLEAN_VERSION,
    text_substring: callbacks.FUNC_TEXT_SUBSTRING,
    text_slice: callbacks.FUNC_TEXT_SLICE,
    text_left: callbacks.FUNC_TEXT_LEFT,
    left: callbacks.FUNC_LEFT,
    text_right: callbacks.FUNC_TEXT_RIGHT,
    right: callbacks.FUNC_RIGHT,
    text_index: callbacks.FUNC_TEXT_INDEX,
    strpos: callbacks.FUNC_STRPOS,
    text_last_index: callbacks.FUNC_TEXT_LAST_INDEX,
    text_contains: callbacks.FUNC_TEXT_CONTAINS,
    text_has_prefix: callbacks.FUNC_TEXT_HAS_PREFIX,
    starts_with: callbacks.FUNC_STARTS_WITH,
    text_has_suffix: callbacks.FUNC_TEXT_HAS_SUFFIX,
    text_count: callbacks.FUNC_TEXT_COUNT,
    text_like: callbacks.FUNC_TEXT_LIKE,
    text_split: callbacks.FUNC_TEXT_SPLIT,
    split_part: callbacks.FUNC_SPLIT_PART,
    text_join: callbacks.FUNC_TEXT_JOIN,
    concat_ws: callbacks.FUNC_CONCAT_WS,
    text_concat: callbacks.FUNC_TEXT_CONCAT,
    concat: callbacks.FUNC_CONCAT,
    text_repeat: callbacks.FUNC_TEXT_REPEAT,
    repeat: callbacks.FUNC_REPEAT,
    text_ltrim: callbacks.FUNC_TEXT_LTRIM,
    ltrim: callbacks.FUNC_LTRIM,
    text_rtrim: callbacks.FUNC_TEXT_RTRIM,
    rtrim: callbacks.FUNC_RTRIM,
    text_trim: callbacks.FUNC_TEXT_TRIM,
    btrim: callbacks.FUNC_BTRIM,
    text_lpad: callbacks.FUNC_TEXT_LPAD,
    lpad: callbacks.FUNC_LPAD,
    text_rpad: callbacks.FUNC_TEXT_RPAD,
    rpad: callbacks.FUNC_RPAD,
    text_upper: callbacks.FUNC_TEXT_UPPER,
    text_lower: callbacks.FUNC_TEXT_LOWER,
    text_title: callbacks.FUNC_TEXT_TITLE,
    text_casefold: callbacks.FUNC_TEXT_CASEFOLD,
    text_replace: callbacks.FUNC_TEXT_REPLACE,
    text_translate: callbacks.FUNC_TEXT_TRANSLATE,
    translate: callbacks.FUNC_TRANSLATE,
    text_reverse: callbacks.FUNC_TEXT_REVERSE,
    reverse: callbacks.FUNC_REVERSE,
    text_length: callbacks.FUNC_TEXT_LENGTH,
    char_length: callbacks.FUNC_CHAR_LENGTH,
    character_length: callbacks.FUNC_CHARACTER_LENGTH,
    text_size: callbacks.FUNC_TEXT_SIZE,
    octet_length: callbacks.FUNC_OCTET_LENGTH,
    text_bitsize: callbacks.FUNC_TEXT_BITSIZE,
    bit_length: callbacks.FUNC_BIT_LENGTH,
};
