.load extensions/color-palette/target/wasm32-wasip2/release/color_palette_extension.component.wasm

/* Smoke test for the `color-palette` extension.
 *
 * Synthetic PNG fixtures (zlib-deflated IDATs, generated by a 50-line
 * python helper  see commit message for the recipe):
 *
 *   PNG_RED_4X4    : 4x4 solid #FF0000
 *   PNG_HALF_4X4   : 4x4, top half #FF0000 / bottom half #0000FF
 *   PNG_TRI_4X3    : 4x3, rows of #FF0000 / #00FF00 / #0000FF
 *   PNG_WHITE_1X1  : 1x1 #FFFFFF (tiny but valid)
 *
 * Acceptance:
 *   1. solid red -> dominant + average + extract(_, 1) all return
 *      a hex string in the red family. k=3 still works (clusters
 *      collapse to the same color, JSON has 3 entries all #ff0000).
 *   2. half-red half-blue -> average is near #7f007f (purple mean);
 *      palette_extract(_, 2) JSON array contains both colors.
 *   3. unparseable / NULL blob -> NULL on every fn.
 *   4. invalid k (0, negative, NULL) -> NULL.
 *   5. palette_version matches Cargo.toml version.
 */

-- ---- Acceptance 1: solid red ----
SELECT palette_dominant(x'89504E470D0A1A0A0000000D4948445200000004000000040802000000269309290000001049444154789C63F8CFC000470CC47100AE930FF1D05F239E0000000049454E44AE426082');
SELECT palette_average_color(x'89504E470D0A1A0A0000000D4948445200000004000000040802000000269309290000001049444154789C63F8CFC000470CC47100AE930FF1D05F239E0000000049454E44AE426082');
SELECT palette_extract(x'89504E470D0A1A0A0000000D4948445200000004000000040802000000269309290000001049444154789C63F8CFC000470CC47100AE930FF1D05F239E0000000049454E44AE426082', 1);

-- ---- Acceptance 2: half red / half blue ----
SELECT palette_average_color(x'89504E470D0A1A0A0000000D4948445200000004000000040802000000269309290000001449444154789C63F8CFC000470C281C342E8203009EA30FF1DC4C0DDE0000000049454E44AE426082');
-- json_array_length is a clean way to assert "we got two colors back"
-- without pinning the exact order of the centroids (k-means seeding
-- is fixed in code but downstream Lab quantization can re-rank colors
-- if the algorithm flips two near-tied clusters).
SELECT json_array_length(palette_extract(x'89504E470D0A1A0A0000000D4948445200000004000000040802000000269309290000001449444154789C63F8CFC000470C281C342E8203009EA30FF1DC4C0DDE0000000049454E44AE426082', 2));

-- ---- Acceptance 3: white 1x1, dominant + average ----
SELECT palette_dominant(x'89504E470D0A1A0A0000000D4948445200000001000000010802000000907753DE0000000C49444154789C63F8FFFF3F0005FE02FE0DEF46B80000000049454E44AE426082');
SELECT palette_average_color(x'89504E470D0A1A0A0000000D4948445200000001000000010802000000907753DE0000000C49444154789C63F8FFFF3F0005FE02FE0DEF46B80000000049454E44AE426082');

-- ---- Acceptance 4: unparseable blob -> NULL ----
SELECT palette_dominant(x'AAAAAAAAAAAAAAAAAAAAAAAA');
SELECT palette_average_color(x'AAAAAAAAAAAAAAAAAAAAAAAA');
SELECT palette_extract(x'AAAAAAAAAAAAAAAAAAAAAAAA', 3);

-- ---- Acceptance 5: NULL passthrough ----
SELECT palette_dominant(NULL);
SELECT palette_average_color(NULL);
SELECT palette_extract(NULL, 3);

-- ---- Acceptance 6: invalid k -> NULL (blob valid, k bad) ----
SELECT palette_extract(x'89504E470D0A1A0A0000000D4948445200000001000000010802000000907753DE0000000C49444154789C63F8FFFF3F0005FE02FE0DEF46B80000000049454E44AE426082', 0);
SELECT palette_extract(x'89504E470D0A1A0A0000000D4948445200000001000000010802000000907753DE0000000C49444154789C63F8FFFF3F0005FE02FE0DEF46B80000000049454E44AE426082', -1);
SELECT palette_extract(x'89504E470D0A1A0A0000000D4948445200000001000000010802000000907753DE0000000C49444154789C63F8FFFF3F0005FE02FE0DEF46B80000000049454E44AE426082', NULL);

-- ---- Acceptance 7: version ----
SELECT palette_version();
