//! Standalone coverage reporter. Runs the matrix and writes
//! `target/extension-smoke-report.md`.
//!
//! Usage:
//!   cargo run -p extension-smoke --release --bin extension-smoke-report
//!
//! Output sections: total fixtures vs inventory, pass/fail
//! breakdown, missing fixtures, missing artifacts.

use extension_smoke::*;
use std::collections::BTreeSet;
use std::path::PathBuf;

#[derive(Default)]
struct Tally {
    pass: usize,
    fail: usize,
    load_fail: usize,
    subproc_err: usize,
    skip_no_artifact: usize,
    skip_no_fixture: usize,
    skip_intentional: usize,
}

fn main() {
    let fixtures = load_fixtures();
    let inv = load_inventory();
    let plugins_in_inventory: BTreeSet<String> =
        inv.iter().map(|r| r.plugin.clone()).collect();
    let plugins_with_fixture: BTreeSet<String> =
        fixtures.extension.keys().cloned().collect();

    let unfixtured: Vec<&String> = plugins_in_inventory
        .iter()
        .filter(|p| !plugins_with_fixture.contains(*p))
        .collect();

    let mut tally = Tally::default();
    let mut failures: Vec<(String, String, String)> = vec![];
    let mut missing_artifacts: Vec<String> = vec![];

    for (plugin, entry) in &fixtures.extension {
        if entry.skip {
            tally.skip_intentional += 1;
            continue;
        }
        let component: PathBuf = match component_path(plugin) {
            Some(p) => p,
            None => {
                missing_artifacts.push(plugin.clone());
                tally.skip_no_artifact += 1;
                continue;
            }
        };
        for (kind_name, probe) in [
            ("scalar", &entry.scalar),
            ("aggregate", &entry.aggregate),
            ("vtab", &entry.vtab),
            ("collation", &entry.collation),
        ] {
            let Some(probe) = probe else { continue };
            let r = run_probe(plugin, &component, kind_name, probe, &entry.grants);
            match r.outcome {
                ProbeOutcome::Pass => tally.pass += 1,
                ProbeOutcome::OutputMismatch { got, want, .. } => {
                    tally.fail += 1;
                    failures.push((
                        plugin.clone(),
                        kind_name.to_string(),
                        format!("mismatch: got={got:?} want={want:?}"),
                    ));
                }
                ProbeOutcome::LoadFailed(d) => {
                    tally.load_fail += 1;
                    failures.push((plugin.clone(), kind_name.to_string(), format!("load failed: {d}")));
                }
                ProbeOutcome::SubprocessError(d) => {
                    tally.subproc_err += 1;
                    failures.push((plugin.clone(), kind_name.to_string(), format!("subproc: {d}")));
                }
            }
        }
    }
    tally.skip_no_fixture = unfixtured.len();

    let report_path = repo_root().join("target/extension-smoke-report.md");
    let _ = std::fs::create_dir_all(report_path.parent().unwrap());
    let body = render_report(&plugins_in_inventory, &fixtures, &tally, &failures, &missing_artifacts, &unfixtured);
    std::fs::write(&report_path, body).expect("write report");
    eprintln!("wrote {}", report_path.display());

    println!("Summary:");
    println!("  plugins in inventory : {}", plugins_in_inventory.len());
    println!("  plugins with fixture : {}", fixtures.extension.len());
    println!("  PASS                 : {}", tally.pass);
    println!("  FAIL (mismatch)      : {}", tally.fail);
    println!("  FAIL (load)          : {}", tally.load_fail);
    println!("  FAIL (subprocess)    : {}", tally.subproc_err);
    println!("  SKIP (no artifact)   : {}", tally.skip_no_artifact);
    println!("  SKIP (no fixture)    : {}", tally.skip_no_fixture);
    println!("  SKIP (intentional)   : {}", tally.skip_intentional);
}

fn render_report(
    plugins_in_inventory: &BTreeSet<String>,
    fixtures: &Fixtures,
    tally: &Tally,
    failures: &[(String, String, String)],
    missing_artifacts: &[String],
    unfixtured: &[&String],
) -> String {
    let mut s = String::new();
    s.push_str("# Extension smoke report\n\n");
    s.push_str("Generated by `cargo run -p extension-smoke --release --bin extension-smoke-report`.\n\n");
    s.push_str("## Summary\n\n");
    s.push_str(&format!("- plugins in inventory: **{}**\n", plugins_in_inventory.len()));
    s.push_str(&format!("- plugins with fixture: **{}**\n", fixtures.extension.len()));
    s.push_str(&format!("- PASS: **{}**\n", tally.pass));
    s.push_str(&format!("- FAIL (mismatch): {}\n", tally.fail));
    s.push_str(&format!("- FAIL (load): {}\n", tally.load_fail));
    s.push_str(&format!("- FAIL (subprocess): {}\n", tally.subproc_err));
    s.push_str(&format!("- SKIP (no artifact built): {}\n", tally.skip_no_artifact));
    s.push_str(&format!("- SKIP (no fixture written): {}\n", tally.skip_no_fixture));
    s.push_str(&format!("- SKIP (intentional): {}\n", tally.skip_intentional));
    s.push_str("\n");
    if !failures.is_empty() {
        s.push_str("## Failures\n\n");
        for (p, k, d) in failures {
            s.push_str(&format!("- **{p}/{k}**: {d}\n"));
        }
        s.push_str("\n");
    }
    if !missing_artifacts.is_empty() {
        s.push_str("## Missing .component.wasm artifacts\n\n");
        s.push_str("These plugins have a fixture but no built component. Build with `cd extensions/<name> && cargo build --target wasm32-wasip2 --release && wasm-tools component new ...`:\n\n");
        for p in missing_artifacts {
            s.push_str(&format!("- {p}\n"));
        }
        s.push_str("\n");
    }
    if !unfixtured.is_empty() {
        s.push_str("## Plugins without fixtures (zero coverage)\n\n");
        for p in unfixtured {
            s.push_str(&format!("- {p}\n"));
        }
        s.push_str("\n");
    }
    s
}
