-- Empty after the 2026-06 survey. The plugin_candidate table is
-- preserved (provenance/scan.py needs it for the registry-handler
-- JSON output to remain shaped consistently), but no rows are
-- seeded. Re-introduce candidates by writing INSERT statements
-- here; scan.py applies this file on every run.
