.load extensions/pgp/target/wasm32-wasip2/release/pgp_extension.component.wasm

/* pgp  OpenPGP key parsing + signature verification (RFC 4880).
 *
 * Fixture: a self-signed Ed25519 (EdDSA) primary + Cv25519 (ECDH)
 *   encryption subkey generated by GnuPG 2.5 for the smoke. Both
 *   keys carry no passphrase. The serialized public key block is
 *   reproduced here as a hex literal so the smoke is deterministic
 *   across runs.
 *
 *   Primary key fingerprint:
 *     0bbc8c118ed3ec80164f243cb16822930f6e3978
 *   Primary key id (low 8 bytes of fingerprint):
 *     b16822930f6e3978
 *   Created: 2026-06-20T18:47:48Z (epoch 1781981268)
 *   User ID: "Smoke Tester <smoke@example.com>"
 *
 * Detached signature fixture: gpg --detach-sign over the literal
 *   bytes of "Hello, World!" using the primary key above.
 *
 * Acceptance:
 *   1. key parsing (id / fp / uids / alg / bits / created)
 *   2. armor <-> binary round-trip
 *   3. detached signature verifies against the message
 *   4. tamper detection: wrong message  0
 *   5. NULL / garbage inputs  NULL (no panic)
 */

CREATE TABLE fixtures(name TEXT PRIMARY KEY, blob BLOB);

/* Binary OpenPGP public-key block. */
INSERT INTO fixtures VALUES (
  'pubkey_bin',
  x'9833046a36e05416092b06010401da470f01010740d2b8c5d83c9b8a3947dc380cb1a9c66f512c864bb3d32fd75cfb27f57d6b6869b420536d6f6b6520546573746572203c736d6f6b65406578616d706c652e636f6d3e88af0413160a00571621040bbc8c118ed3ec80164f243cb16822930f6e397805026a36e0541b14800000000004000e6d616e75322c322e352b312e31322c302c33021b23050b0908070202220206150a09080b020416020301021e07021780000a0910b16822930f6e3978ba0a0100a4ca68e8d0905769a555955013bf95ba2f946e8860e016736bed31dc00223ae70100d3259f723985da063e71d88dbd18f2f8bc5bc5d89f3bbfa4ca19d5ed94fe8f03b838046a36e054120a2b0601040197550105010107403225f1fc1f3d3723462a706c005cb61dcdd07f71327717f3e1392fd29d2ec6120301080788940418160a003c1621040bbc8c118ed3ec80164f243cb16822930f6e397805026a36e0541b14800000000004000e6d616e75322c322e352b312e31322c302c33021b0c000a0910b16822930f6e397866e900ff4bb4fe5607211588b7848d293d393e36f82c8d5e5e14d5fc1f19b7ab7909755400ff717d79a69b2baeea773ffe89937e20a35cdc3fd4d23c5a35f133bdc93547df09'
);

/* Detached binary signature over "Hello, World!". */
INSERT INTO fixtures VALUES (
  'sig_bin',
  x'88910400160a00391621040bbc8c118ed3ec80164f243cb16822930f6e397805026a36e0751b14800000000004000e6d616e75322c322e352b312e31322c302c33000a0910b16822930f6e39787d4b00ff6118c86524739d5859cdb941cdb74298f5507d9765c0363b0e2cd59bdda1cfa700fe2ff528491f0959d76ab7478dff104d97845712c6242f6054f17d5a1327d8840d'
);

/* Garbage  every parse fn should NULL. */
INSERT INTO fixtures VALUES ('garbage', x'deadbeefcafef00d');

/* Acceptance 1  field extractors against the binary public key. */
SELECT pgp_key_id(blob)          FROM fixtures WHERE name='pubkey_bin';
SELECT pgp_key_fingerprint(blob) FROM fixtures WHERE name='pubkey_bin';
SELECT pgp_key_user_ids(blob)    FROM fixtures WHERE name='pubkey_bin';
SELECT pgp_key_algorithm(blob)   FROM fixtures WHERE name='pubkey_bin';
SELECT pgp_key_bits(blob)        FROM fixtures WHERE name='pubkey_bin';
SELECT pgp_key_created(blob)     FROM fixtures WHERE name='pubkey_bin';

/* Acceptance 2  armor round-trip. binary  armored  binary must
 * give back the exact original packet stream (armor is just a
 * base64 + CRC envelope). */
SELECT pgp_armor_to_binary(pgp_binary_to_armor(blob, 'public')) = blob
  FROM fixtures WHERE name='pubkey_bin';

/* The armored form must parse to the same fingerprint as the
 * binary form  proves the TEXT/armor coercion path on key fns. */
SELECT pgp_key_fingerprint(pgp_binary_to_armor(blob, 'public'))
  = pgp_key_fingerprint(blob)
  FROM fixtures WHERE name='pubkey_bin';

/* Armored output starts with the standard public-key header. */
SELECT substr(pgp_binary_to_armor(blob, 'public'), 1, 36)
  FROM fixtures WHERE name='pubkey_bin';

/* Acceptance 3  signature verifies. */
SELECT pgp_verify(
  (SELECT blob FROM fixtures WHERE name='sig_bin'),
  'Hello, World!',
  (SELECT blob FROM fixtures WHERE name='pubkey_bin')
);

/* Acceptance 4  tamper detection: changing one byte of the
 * message MUST fail the verify. */
SELECT pgp_verify(
  (SELECT blob FROM fixtures WHERE name='sig_bin'),
  'Hello, World?',
  (SELECT blob FROM fixtures WHERE name='pubkey_bin')
);

/* Wrong key (garbage)  0, not NULL  pgp_verify always returns
 * INTEGER per spec. */
SELECT pgp_verify(
  (SELECT blob FROM fixtures WHERE name='sig_bin'),
  'Hello, World!',
  (SELECT blob FROM fixtures WHERE name='garbage')
);

/* Acceptance 5  garbage input  NULL on every parse fn (no panic). */
SELECT pgp_key_id(blob)          FROM fixtures WHERE name='garbage';
SELECT pgp_key_fingerprint(blob) FROM fixtures WHERE name='garbage';
SELECT pgp_key_user_ids(blob)    FROM fixtures WHERE name='garbage';
SELECT pgp_key_algorithm(blob)   FROM fixtures WHERE name='garbage';
SELECT pgp_key_bits(blob)        FROM fixtures WHERE name='garbage';
SELECT pgp_key_created(blob)     FROM fixtures WHERE name='garbage';

/* NULL input  NULL. */
SELECT pgp_key_id(NULL);
SELECT pgp_armor_to_binary(NULL);

/* pgp_version is non-empty. */
SELECT length(pgp_version()) > 0;
