//! Password hashing scalars: Argon2id, bcrypt, PBKDF2, scrypt.
//!
//! Companion to the `jwt` extension and the auth wasm handler.
//! jwt covers the token half of an auth flow; this covers the
//! "did this password match the stored hash" half.
//!
//! Function surface (PLAN-more-extensions.md  1):
//!
//!   argon2_hash(password, [params_json])    -> TEXT (PHC string)
//!   argon2_verify(password, phc)            -> INTEGER (0/1)
//!   bcrypt_hash(password, [cost])           -> TEXT
//!   bcrypt_verify(password, hash)           -> INTEGER (0/1)
//!   pbkdf2_sha256(password, salt, iter, dklen) -> BLOB
//!   pbkdf2_sha512(password, salt, iter, dklen) -> BLOB
//!   scrypt_hash(password, [params_json])    -> TEXT (PHC string)
//!   scrypt_verify(password, phc)            -> INTEGER (0/1)
//!   pwhash_version()                        -> TEXT
//!
//! `params_json` is an optional JSON object  unspecified fields fall
//! back to OWASP-recommended defaults for production. Argon2 uses
//! `{"m":memory_kib,"t":iterations,"p":parallelism}` and scrypt uses
//! `{"ln":log_n,"r":blocksize,"p":parallelism,"len":dklen}`.
//!
//! All `*_verify` fns return 0 on any failure mode (bad PHC, wrong
//! password, unsupported alg)  no exception. Matches the
//! crypto-auth precedent and lets callers use the result directly
//! in WHERE / CASE without try/catch wrappers.
//!
//! PBKDF2 has no PHC envelope here  it returns the raw derived key
//! as a BLOB so the RFC 6070 test vectors match byte-for-byte. If
//! you want a PHC-style stored value, use Argon2 / bcrypt / scrypt.

extern crate alloc;

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

// ─────────────── Argon2 ───────────────

/// OWASP-recommended Argon2id defaults (2024 OWASP cheat sheet,
/// "Argon2id"): m=19 MiB, t=2 iterations, p=1 lane. The argon2
/// crate's `Argon2::default()` uses the same values, so we lean on
/// it when `params_json` is None.
fn argon2_params_from_json(s: Option<&str>) -> Result<argon2::Params, String> {
    let Some(s) = s else {
        return Ok(argon2::Params::default());
    };
    let v: serde_json::Value =
        serde_json::from_str(s).map_err(|e| format!("argon2 params JSON: {e}"))?;
    let obj = v
        .as_object()
        .ok_or_else(|| "argon2 params must be a JSON object".to_string())?;
    let m_cost = obj
        .get("m")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(argon2::Params::DEFAULT_M_COST);
    let t_cost = obj
        .get("t")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(argon2::Params::DEFAULT_T_COST);
    let p_cost = obj
        .get("p")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(argon2::Params::DEFAULT_P_COST);
    argon2::Params::new(m_cost, t_cost, p_cost, None)
        .map_err(|e| format!("argon2 params invalid: {e}"))
}

pub fn argon2_hash(password: &str, params_json: Option<&str>) -> Result<String, String> {
    use argon2::password_hash::{rand_core::OsRng, PasswordHasher, SaltString};
    use argon2::{Algorithm, Argon2, Version};
    let params = argon2_params_from_json(params_json)?;
    let salt = SaltString::generate(&mut OsRng);
    let a = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
    a.hash_password(password.as_bytes(), &salt)
        .map(|h| h.to_string())
        .map_err(|e| format!("argon2_hash: {e}"))
}

pub fn argon2_verify(password: &str, phc: &str) -> bool {
    use argon2::password_hash::{PasswordHash, PasswordVerifier};
    use argon2::Argon2;
    let Ok(parsed) = PasswordHash::new(phc) else {
        return false;
    };
    Argon2::default()
        .verify_password(password.as_bytes(), &parsed)
        .is_ok()
}

// ─────────────── bcrypt ───────────────

/// OWASP recommends cost  10 for bcrypt; we ship 12 as the default
/// because cost-10 hashes can be brute-forced on modern GPUs in
/// under a week. Callers can pass an explicit cost down to 4 (the
/// crate's floor) for cheap test/smoke runs.
pub fn bcrypt_hash(password: &str, cost: Option<u32>) -> Result<String, String> {
    let c = cost.unwrap_or(12);
    bcrypt::hash(password, c).map_err(|e| format!("bcrypt_hash: {e}"))
}

pub fn bcrypt_verify(password: &str, hash: &str) -> bool {
    bcrypt::verify(password, hash).unwrap_or(false)
}

// ─────────────── PBKDF2 ───────────────

pub fn pbkdf2_sha256(password: &[u8], salt: &[u8], iter: u32, dklen: usize) -> Vec<u8> {
    let mut out = alloc::vec![0u8; dklen];
    // pbkdf2_hmac is infallible aside from a degenerate zero-iter
    // case, which the upstream crate handles gracefully (it just
    // returns the unmodified buffer). RFC 6070's reference vectors
    // were generated by the same construction.
    pbkdf2::pbkdf2_hmac::<sha2::Sha256>(password, salt, iter, &mut out);
    out
}

pub fn pbkdf2_sha512(password: &[u8], salt: &[u8], iter: u32, dklen: usize) -> Vec<u8> {
    let mut out = alloc::vec![0u8; dklen];
    pbkdf2::pbkdf2_hmac::<sha2::Sha512>(password, salt, iter, &mut out);
    out
}

// ─────────────── scrypt ───────────────

/// scrypt defaults from OWASP 2024 cheat sheet: log_n=17 (N=131072),
/// r=8, p=1. dklen defaults to 32 (PHC envelope encodes the salt
/// + dklen so verify recovers it).
struct ScryptParamsJson {
    log_n: u8,
    r: u32,
    p: u32,
    len: usize,
}

fn scrypt_params_from_json(s: Option<&str>) -> Result<ScryptParamsJson, String> {
    let default = ScryptParamsJson {
        log_n: 17,
        r: 8,
        p: 1,
        len: 32,
    };
    let Some(s) = s else {
        return Ok(default);
    };
    let v: serde_json::Value =
        serde_json::from_str(s).map_err(|e| format!("scrypt params JSON: {e}"))?;
    let obj = v
        .as_object()
        .ok_or_else(|| "scrypt params must be a JSON object".to_string())?;
    let log_n = obj
        .get("ln")
        .and_then(|v| v.as_u64())
        .map(|n| n as u8)
        .unwrap_or(default.log_n);
    let r = obj
        .get("r")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(default.r);
    let p = obj
        .get("p")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .unwrap_or(default.p);
    let len = obj
        .get("len")
        .and_then(|v| v.as_u64())
        .map(|n| n as usize)
        .unwrap_or(default.len);
    Ok(ScryptParamsJson { log_n, r, p, len })
}

pub fn scrypt_hash(password: &str, params_json: Option<&str>) -> Result<String, String> {
    use password_hash::{rand_core::OsRng, PasswordHasher, SaltString};
    let p = scrypt_params_from_json(params_json)?;
    let salt = SaltString::generate(&mut OsRng);
    let sp = scrypt::Params::new(p.log_n, p.r, p.p, p.len)
        .map_err(|e| format!("scrypt params invalid: {e}"))?;
    // Scrypt's PHC-string adapter is the `Scrypt` unit struct from
    // the "simple" feature. `hash_password_customized` is the only
    // entry point that lets us pass our own scrypt::Params (the
    // shorter `hash_password` defaults to the crate's params).
    let phc = scrypt::Scrypt
        .hash_password_customized(password.as_bytes(), None, None, sp, &salt)
        .map_err(|e| format!("scrypt_hash: {e}"))?;
    Ok(phc.to_string())
}

pub fn scrypt_verify(password: &str, phc: &str) -> bool {
    use password_hash::{PasswordHash, PasswordVerifier};
    let Ok(parsed) = PasswordHash::new(phc) else {
        return false;
    };
    scrypt::Scrypt
        .verify_password(password.as_bytes(), &parsed)
        .is_ok()
}

// ─────────────── wasm component export ───────────────

#[cfg(target_arch = "wasm32")]
mod wasm_export {
    use alloc::format;
    use alloc::string::{String, ToString};
    use alloc::vec::Vec;

    mod bindings {
        wit_bindgen::generate!({
            path: "../../sqlite-loader-wit/wit",
            world: "minimal",
            generate_all,
        });
    }

    use bindings::exports::sqlite::extension::metadata::{
        Guest as MetadataGuest, Manifest, ScalarFunctionSpec,
    };
    use bindings::exports::sqlite::extension::scalar_function::Guest as ScalarFunctionGuest;
    use bindings::sqlite::extension::types::{FunctionFlags, SqlValue};

    // Each function family gets two FIDs when it has an optional
    // last arg  the dispatcher routes 1-arg vs 2-arg by FID.
    const FID_ARGON2_HASH_1: u64 = 1;
    const FID_ARGON2_HASH_2: u64 = 2;
    const FID_ARGON2_VERIFY: u64 = 3;
    const FID_BCRYPT_HASH_1: u64 = 4;
    const FID_BCRYPT_HASH_2: u64 = 5;
    const FID_BCRYPT_VERIFY: u64 = 6;
    const FID_PBKDF2_SHA256: u64 = 7;
    const FID_PBKDF2_SHA512: u64 = 8;
    const FID_SCRYPT_HASH_1: u64 = 9;
    const FID_SCRYPT_HASH_2: u64 = 10;
    const FID_SCRYPT_VERIFY: u64 = 11;
    const FID_VERSION: u64 = 12;

    struct Ext;

    fn arg_text(args: &[SqlValue], i: usize, fname: &str) -> Result<String, String> {
        match args.get(i) {
            Some(SqlValue::Text(s)) => Ok(s.clone()),
            _ => Err(format!("{fname}: TEXT arg at {i}")),
        }
    }

    /// password / salt: accept TEXT (UTF-8) or BLOB (raw bytes).
    /// RFC 6070's PBKDF2 vectors are ASCII so TEXT is the common
    /// path, but binary salts are a legit production case.
    fn arg_bytes(args: &[SqlValue], i: usize, fname: &str) -> Result<Vec<u8>, String> {
        match args.get(i) {
            Some(SqlValue::Text(s)) => Ok(s.as_bytes().to_vec()),
            Some(SqlValue::Blob(b)) => Ok(b.clone()),
            _ => Err(format!("{fname}: TEXT or BLOB arg at {i}")),
        }
    }

    fn arg_uint(args: &[SqlValue], i: usize, fname: &str) -> Result<u32, String> {
        match args.get(i) {
            Some(SqlValue::Integer(n)) if *n >= 0 => Ok(*n as u32),
            _ => Err(format!("{fname}: non-negative INTEGER arg at {i}")),
        }
    }

    impl MetadataGuest for Ext {
        fn describe() -> Manifest {
            let det = FunctionFlags::DETERMINISTIC;
            let nd = FunctionFlags::empty();
            let s = |id, name: &str, n: i32, f: FunctionFlags| ScalarFunctionSpec {
                id,
                name: name.into(),
                num_args: n,
                func_flags: f,
            };
            Manifest {
                name: "pwhash".to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
                scalar_functions: alloc::vec![
                    // Argon2  hash is non-det (random salt); verify
                    // is pure once the PHC string is materialized.
                    s(FID_ARGON2_HASH_1, "argon2_hash", 1, nd),
                    s(FID_ARGON2_HASH_2, "argon2_hash", 2, nd),
                    s(FID_ARGON2_VERIFY, "argon2_verify", 2, det),
                    // bcrypt
                    s(FID_BCRYPT_HASH_1, "bcrypt_hash", 1, nd),
                    s(FID_BCRYPT_HASH_2, "bcrypt_hash", 2, nd),
                    s(FID_BCRYPT_VERIFY, "bcrypt_verify", 2, det),
                    // PBKDF2 raw blob  fully deterministic given
                    // (password, salt, iter, dklen).
                    s(FID_PBKDF2_SHA256, "pbkdf2_sha256", 4, det),
                    s(FID_PBKDF2_SHA512, "pbkdf2_sha512", 4, det),
                    // scrypt
                    s(FID_SCRYPT_HASH_1, "scrypt_hash", 1, nd),
                    s(FID_SCRYPT_HASH_2, "scrypt_hash", 2, nd),
                    s(FID_SCRYPT_VERIFY, "scrypt_verify", 2, det),
                    s(FID_VERSION, "pwhash_version", 0, det),
                ],
                aggregate_functions: alloc::vec![],
                collations: alloc::vec![],
                vtabs: alloc::vec![],
                has_authorizer: false,
                has_update_hook: false,
                has_commit_hook: false,
                has_wal_hook: false,
                wal_hook_id: 0,
                dot_commands: alloc::vec![],
                declared_capabilities: alloc::vec![],
                optional_capabilities: alloc::vec![],
                preferred_prefix: None,
                prefix_expansion: None,
            }
        }
    }

    impl ScalarFunctionGuest for Ext {
        fn call(func_id: u64, args: Vec<SqlValue>) -> Result<SqlValue, String> {
            match func_id {
                FID_ARGON2_HASH_1 => {
                    let p = arg_text(&args, 0, "argon2_hash")?;
                    super::argon2_hash(&p, None).map(SqlValue::Text)
                }
                FID_ARGON2_HASH_2 => {
                    let p = arg_text(&args, 0, "argon2_hash")?;
                    let pj = arg_text(&args, 1, "argon2_hash")?;
                    super::argon2_hash(&p, Some(&pj)).map(SqlValue::Text)
                }
                FID_ARGON2_VERIFY => {
                    let p = arg_text(&args, 0, "argon2_verify")?;
                    let phc = arg_text(&args, 1, "argon2_verify")?;
                    Ok(SqlValue::Integer(super::argon2_verify(&p, &phc) as i64))
                }
                FID_BCRYPT_HASH_1 => {
                    let p = arg_text(&args, 0, "bcrypt_hash")?;
                    super::bcrypt_hash(&p, None).map(SqlValue::Text)
                }
                FID_BCRYPT_HASH_2 => {
                    let p = arg_text(&args, 0, "bcrypt_hash")?;
                    let cost = arg_uint(&args, 1, "bcrypt_hash")?;
                    super::bcrypt_hash(&p, Some(cost)).map(SqlValue::Text)
                }
                FID_BCRYPT_VERIFY => {
                    let p = arg_text(&args, 0, "bcrypt_verify")?;
                    let hash = arg_text(&args, 1, "bcrypt_verify")?;
                    Ok(SqlValue::Integer(super::bcrypt_verify(&p, &hash) as i64))
                }
                FID_PBKDF2_SHA256 => {
                    let p = arg_bytes(&args, 0, "pbkdf2_sha256")?;
                    let s = arg_bytes(&args, 1, "pbkdf2_sha256")?;
                    let it = arg_uint(&args, 2, "pbkdf2_sha256")?;
                    let dk = arg_uint(&args, 3, "pbkdf2_sha256")? as usize;
                    Ok(SqlValue::Blob(super::pbkdf2_sha256(&p, &s, it, dk)))
                }
                FID_PBKDF2_SHA512 => {
                    let p = arg_bytes(&args, 0, "pbkdf2_sha512")?;
                    let s = arg_bytes(&args, 1, "pbkdf2_sha512")?;
                    let it = arg_uint(&args, 2, "pbkdf2_sha512")?;
                    let dk = arg_uint(&args, 3, "pbkdf2_sha512")? as usize;
                    Ok(SqlValue::Blob(super::pbkdf2_sha512(&p, &s, it, dk)))
                }
                FID_SCRYPT_HASH_1 => {
                    let p = arg_text(&args, 0, "scrypt_hash")?;
                    super::scrypt_hash(&p, None).map(SqlValue::Text)
                }
                FID_SCRYPT_HASH_2 => {
                    let p = arg_text(&args, 0, "scrypt_hash")?;
                    let pj = arg_text(&args, 1, "scrypt_hash")?;
                    super::scrypt_hash(&p, Some(&pj)).map(SqlValue::Text)
                }
                FID_SCRYPT_VERIFY => {
                    let p = arg_text(&args, 0, "scrypt_verify")?;
                    let phc = arg_text(&args, 1, "scrypt_verify")?;
                    Ok(SqlValue::Integer(super::scrypt_verify(&p, &phc) as i64))
                }
                FID_VERSION => Ok(SqlValue::Text(env!("CARGO_PKG_VERSION").to_string())),
                other => Err(format!("pwhash: unknown func id {other}")),
            }
        }
    }

    bindings::export!(Ext with_types_in bindings);
}
