import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Explicit sidebar. Order matters here, NOT in sidebar_position
// frontmatter (which is only consulted when a sidebar is
// autogenerated).
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'concepts/extensions',
        'concepts/bundles',
        'concepts/prefixes',
        'concepts/cas-cache',
      ],
    },
    'roadmap',
    {
      type: 'category',
      label: 'Plans (source of truth)',
      collapsed: true,
      items: [
        'plans/PLAN-bundles',
        'plans/PLAN-prefixes',
        'plans/PLAN-followups',
        'plans/PLAN-browser-runtime',
        'plans/PLAN-wal-archive-extension',
        'plans/PLAN-tvm-integration',
        'plans/PLAN-wasmmachine',
        'plans/PLAN-interactive-capture',
        'plans/PLAN-benchmarks',
        'plans/PLAN-release-readiness-perf-ux',
        'plans/PLAN-release-readiness-testing',
        'plans/PLAN-release-readiness-code-health',
        'plans/PLAN-speculative',
      ],
    },
  ],
};

export default sidebars;
