import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Step 4 will replace this with an explicit, hand-rolled structure.
// For step 1 the autogenerated sidebar is enough to make the build
// pass + verify the scaffold.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
