//! Bundled IANA root-zone TLD snapshot.
//!
//! Each row is `(tld_punycode, kind, country_alpha2)`:
//!   * `tld_punycode` is the IANA-canonical lowercase ASCII form. For
//!     IDN ccTLDs this is the `xn--` punycode form; we add a separate
//!     row for the Unicode form pointing back at the same canonical
//!     entry via the `aliases` table below.
//!   * `kind` is one of: "gtld", "cctld", "sponsored", "infrastructure",
//!     "reserved".
//!   * `country_alpha2` is the ISO 3166-1 alpha-2 country code for
//!     ccTLDs, "" for everything else.
//!
//! Source: IANA Root Zone Database Type categorisation as of 2024.
//! Snapshot rationale: the spec explicitly allows "bundle the IANA
//! list" because the `iana-tld` crate suggested in the spec does not
//! exist on crates.io; embedding the list in source is the only
//! offline, no-network option that still satisfies the brief.

/// (tld_canonical_lowercase, kind, country_alpha2 or "")
pub const TLDS: &[(&str, &str, &str)] = &[
    // ─────────────── infrastructure ───────────────
    ("arpa", "infrastructure", ""),

    // ─────────────── reserved (RFC 2606 + RFC 6761) ───────────────
    ("example", "reserved", ""),
    ("invalid", "reserved", ""),
    ("localhost", "reserved", ""),
    ("test", "reserved", ""),

    // ─────────────── sponsored gTLDs (legacy sTLDs) ───────────────
    ("aero", "sponsored", ""),
    ("asia", "sponsored", ""),
    ("cat", "sponsored", ""),
    ("coop", "sponsored", ""),
    ("edu", "sponsored", ""),
    ("gov", "sponsored", ""),
    ("int", "sponsored", ""),
    ("jobs", "sponsored", ""),
    ("mil", "sponsored", ""),
    ("museum", "sponsored", ""),
    ("post", "sponsored", ""),
    ("tel", "sponsored", ""),
    ("travel", "sponsored", ""),
    ("xxx", "sponsored", ""),

    // ─────────────── generic gTLDs (legacy + popular new-gTLDs) ───────────────
    ("com", "gtld", ""),
    ("net", "gtld", ""),
    ("org", "gtld", ""),
    ("biz", "gtld", ""),
    ("info", "gtld", ""),
    ("name", "gtld", ""),
    ("pro", "gtld", ""),
    // Popular new-gTLD slice  not exhaustive, but covers the
    // commercially significant subset asked for in the brief.
    ("app", "gtld", ""),
    ("dev", "gtld", ""),
    ("xyz", "gtld", ""),
    ("io", "cctld", "IO"), // British Indian Ocean Territory  also under cctld below
    ("ai", "cctld", "AI"),
    ("online", "gtld", ""),
    ("site", "gtld", ""),
    ("shop", "gtld", ""),
    ("blog", "gtld", ""),
    ("club", "gtld", ""),
    ("store", "gtld", ""),
    ("tech", "gtld", ""),
    ("space", "gtld", ""),
    ("page", "gtld", ""),
    ("cloud", "gtld", ""),
    ("art", "gtld", ""),
    ("design", "gtld", ""),
    ("email", "gtld", ""),
    ("link", "gtld", ""),
    ("live", "gtld", ""),
    ("news", "gtld", ""),
    ("today", "gtld", ""),
    ("world", "gtld", ""),
    ("global", "gtld", ""),
    ("digital", "gtld", ""),
    ("agency", "gtld", ""),
    ("group", "gtld", ""),
    ("media", "gtld", ""),
    ("works", "gtld", ""),
    ("solutions", "gtld", ""),
    ("services", "gtld", ""),
    ("studio", "gtld", ""),
    ("center", "gtld", ""),
    ("company", "gtld", ""),
    ("network", "gtld", ""),
    ("systems", "gtld", ""),
    ("tools", "gtld", ""),
    ("zone", "gtld", ""),
    ("ninja", "gtld", ""),
    ("guru", "gtld", ""),
    ("photography", "gtld", ""),
    ("photo", "gtld", ""),
    ("video", "gtld", ""),
    ("music", "gtld", ""),
    ("movie", "gtld", ""),
    ("game", "gtld", ""),
    ("games", "gtld", ""),
    ("fun", "gtld", ""),
    ("life", "gtld", ""),
    ("love", "gtld", ""),
    ("rocks", "gtld", ""),
    ("wtf", "gtld", ""),
    ("lol", "gtld", ""),

    // ─────────────── country-code TLDs (ISO 3166-1 alpha-2) ───────────────
    ("ac", "cctld", "SH"), // Ascension Island; managed by Saint Helena
    ("ad", "cctld", "AD"),
    ("ae", "cctld", "AE"),
    ("af", "cctld", "AF"),
    ("ag", "cctld", "AG"),
    ("al", "cctld", "AL"),
    ("am", "cctld", "AM"),
    ("ao", "cctld", "AO"),
    ("aq", "cctld", "AQ"),
    ("ar", "cctld", "AR"),
    ("as", "cctld", "AS"),
    ("at", "cctld", "AT"),
    ("au", "cctld", "AU"),
    ("aw", "cctld", "AW"),
    ("ax", "cctld", "AX"),
    ("az", "cctld", "AZ"),
    ("ba", "cctld", "BA"),
    ("bb", "cctld", "BB"),
    ("bd", "cctld", "BD"),
    ("be", "cctld", "BE"),
    ("bf", "cctld", "BF"),
    ("bg", "cctld", "BG"),
    ("bh", "cctld", "BH"),
    ("bi", "cctld", "BI"),
    ("bj", "cctld", "BJ"),
    ("bm", "cctld", "BM"),
    ("bn", "cctld", "BN"),
    ("bo", "cctld", "BO"),
    ("br", "cctld", "BR"),
    ("bs", "cctld", "BS"),
    ("bt", "cctld", "BT"),
    ("bw", "cctld", "BW"),
    ("by", "cctld", "BY"),
    ("bz", "cctld", "BZ"),
    ("ca", "cctld", "CA"),
    ("cc", "cctld", "CC"),
    ("cd", "cctld", "CD"),
    ("cf", "cctld", "CF"),
    ("cg", "cctld", "CG"),
    ("ch", "cctld", "CH"),
    ("ci", "cctld", "CI"),
    ("ck", "cctld", "CK"),
    ("cl", "cctld", "CL"),
    ("cm", "cctld", "CM"),
    ("cn", "cctld", "CN"),
    ("co", "cctld", "CO"),
    ("cr", "cctld", "CR"),
    ("cu", "cctld", "CU"),
    ("cv", "cctld", "CV"),
    ("cw", "cctld", "CW"),
    ("cx", "cctld", "CX"),
    ("cy", "cctld", "CY"),
    ("cz", "cctld", "CZ"),
    ("de", "cctld", "DE"),
    ("dj", "cctld", "DJ"),
    ("dk", "cctld", "DK"),
    ("dm", "cctld", "DM"),
    ("do", "cctld", "DO"),
    ("dz", "cctld", "DZ"),
    ("ec", "cctld", "EC"),
    ("ee", "cctld", "EE"),
    ("eg", "cctld", "EG"),
    ("er", "cctld", "ER"),
    ("es", "cctld", "ES"),
    ("et", "cctld", "ET"),
    ("eu", "cctld", "EU"), // sovereignty: European Union, ISO 3166-1 reserved
    ("fi", "cctld", "FI"),
    ("fj", "cctld", "FJ"),
    ("fk", "cctld", "FK"),
    ("fm", "cctld", "FM"),
    ("fo", "cctld", "FO"),
    ("fr", "cctld", "FR"),
    ("ga", "cctld", "GA"),
    ("gd", "cctld", "GD"),
    ("ge", "cctld", "GE"),
    ("gf", "cctld", "GF"),
    ("gg", "cctld", "GG"),
    ("gh", "cctld", "GH"),
    ("gi", "cctld", "GI"),
    ("gl", "cctld", "GL"),
    ("gm", "cctld", "GM"),
    ("gn", "cctld", "GN"),
    ("gp", "cctld", "GP"),
    ("gq", "cctld", "GQ"),
    ("gr", "cctld", "GR"),
    ("gs", "cctld", "GS"),
    ("gt", "cctld", "GT"),
    ("gu", "cctld", "GU"),
    ("gw", "cctld", "GW"),
    ("gy", "cctld", "GY"),
    ("hk", "cctld", "HK"),
    ("hm", "cctld", "HM"),
    ("hn", "cctld", "HN"),
    ("hr", "cctld", "HR"),
    ("ht", "cctld", "HT"),
    ("hu", "cctld", "HU"),
    ("id", "cctld", "ID"),
    ("ie", "cctld", "IE"),
    ("il", "cctld", "IL"),
    ("im", "cctld", "IM"),
    ("in", "cctld", "IN"),
    ("iq", "cctld", "IQ"),
    ("ir", "cctld", "IR"),
    ("is", "cctld", "IS"),
    ("it", "cctld", "IT"),
    ("je", "cctld", "JE"),
    ("jm", "cctld", "JM"),
    ("jo", "cctld", "JO"),
    ("jp", "cctld", "JP"),
    ("ke", "cctld", "KE"),
    ("kg", "cctld", "KG"),
    ("kh", "cctld", "KH"),
    ("ki", "cctld", "KI"),
    ("km", "cctld", "KM"),
    ("kn", "cctld", "KN"),
    ("kp", "cctld", "KP"),
    ("kr", "cctld", "KR"),
    ("kw", "cctld", "KW"),
    ("ky", "cctld", "KY"),
    ("kz", "cctld", "KZ"),
    ("la", "cctld", "LA"),
    ("lb", "cctld", "LB"),
    ("lc", "cctld", "LC"),
    ("li", "cctld", "LI"),
    ("lk", "cctld", "LK"),
    ("lr", "cctld", "LR"),
    ("ls", "cctld", "LS"),
    ("lt", "cctld", "LT"),
    ("lu", "cctld", "LU"),
    ("lv", "cctld", "LV"),
    ("ly", "cctld", "LY"),
    ("ma", "cctld", "MA"),
    ("mc", "cctld", "MC"),
    ("md", "cctld", "MD"),
    ("me", "cctld", "ME"),
    ("mg", "cctld", "MG"),
    ("mh", "cctld", "MH"),
    ("mk", "cctld", "MK"),
    ("ml", "cctld", "ML"),
    ("mm", "cctld", "MM"),
    ("mn", "cctld", "MN"),
    ("mo", "cctld", "MO"),
    ("mp", "cctld", "MP"),
    ("mq", "cctld", "MQ"),
    ("mr", "cctld", "MR"),
    ("ms", "cctld", "MS"),
    ("mt", "cctld", "MT"),
    ("mu", "cctld", "MU"),
    ("mv", "cctld", "MV"),
    ("mw", "cctld", "MW"),
    ("mx", "cctld", "MX"),
    ("my", "cctld", "MY"),
    ("mz", "cctld", "MZ"),
    ("na", "cctld", "NA"),
    ("nc", "cctld", "NC"),
    ("ne", "cctld", "NE"),
    ("nf", "cctld", "NF"),
    ("ng", "cctld", "NG"),
    ("ni", "cctld", "NI"),
    ("nl", "cctld", "NL"),
    ("no", "cctld", "NO"),
    ("np", "cctld", "NP"),
    ("nr", "cctld", "NR"),
    ("nu", "cctld", "NU"),
    ("nz", "cctld", "NZ"),
    ("om", "cctld", "OM"),
    ("pa", "cctld", "PA"),
    ("pe", "cctld", "PE"),
    ("pf", "cctld", "PF"),
    ("pg", "cctld", "PG"),
    ("ph", "cctld", "PH"),
    ("pk", "cctld", "PK"),
    ("pl", "cctld", "PL"),
    ("pm", "cctld", "PM"),
    ("pn", "cctld", "PN"),
    ("pr", "cctld", "PR"),
    ("ps", "cctld", "PS"),
    ("pt", "cctld", "PT"),
    ("pw", "cctld", "PW"),
    ("py", "cctld", "PY"),
    ("qa", "cctld", "QA"),
    ("re", "cctld", "RE"),
    ("ro", "cctld", "RO"),
    ("rs", "cctld", "RS"),
    ("ru", "cctld", "RU"),
    ("rw", "cctld", "RW"),
    ("sa", "cctld", "SA"),
    ("sb", "cctld", "SB"),
    ("sc", "cctld", "SC"),
    ("sd", "cctld", "SD"),
    ("se", "cctld", "SE"),
    ("sg", "cctld", "SG"),
    ("sh", "cctld", "SH"),
    ("si", "cctld", "SI"),
    ("sk", "cctld", "SK"),
    ("sl", "cctld", "SL"),
    ("sm", "cctld", "SM"),
    ("sn", "cctld", "SN"),
    ("so", "cctld", "SO"),
    ("sr", "cctld", "SR"),
    ("ss", "cctld", "SS"),
    ("st", "cctld", "ST"),
    ("su", "cctld", "SU"), // legacy Soviet Union; still in root zone
    ("sv", "cctld", "SV"),
    ("sx", "cctld", "SX"),
    ("sy", "cctld", "SY"),
    ("sz", "cctld", "SZ"),
    ("tc", "cctld", "TC"),
    ("td", "cctld", "TD"),
    ("tf", "cctld", "TF"),
    ("tg", "cctld", "TG"),
    ("th", "cctld", "TH"),
    ("tj", "cctld", "TJ"),
    ("tk", "cctld", "TK"),
    ("tl", "cctld", "TL"),
    ("tm", "cctld", "TM"),
    ("tn", "cctld", "TN"),
    ("to", "cctld", "TO"),
    ("tr", "cctld", "TR"),
    ("tt", "cctld", "TT"),
    ("tv", "cctld", "TV"),
    ("tw", "cctld", "TW"),
    ("tz", "cctld", "TZ"),
    ("ua", "cctld", "UA"),
    ("ug", "cctld", "UG"),
    ("uk", "cctld", "GB"), // United Kingdom uses GB in ISO 3166-1
    ("us", "cctld", "US"),
    ("uy", "cctld", "UY"),
    ("uz", "cctld", "UZ"),
    ("va", "cctld", "VA"),
    ("vc", "cctld", "VC"),
    ("ve", "cctld", "VE"),
    ("vg", "cctld", "VG"),
    ("vi", "cctld", "VI"),
    ("vn", "cctld", "VN"),
    ("vu", "cctld", "VU"),
    ("wf", "cctld", "WF"),
    ("ws", "cctld", "WS"),
    ("ye", "cctld", "YE"),
    ("yt", "cctld", "YT"),
    ("za", "cctld", "ZA"),
    ("zm", "cctld", "ZM"),
    ("zw", "cctld", "ZW"),

    // ─────────────── IDN ccTLDs (punycode form, with Unicode aliases below) ───────────────
    ("xn--lgbbat1ad8j", "cctld", "DZ"), // .الجزائر  Algeria
    ("xn--mgbcpq6gpa1a", "cctld", "BH"), // .البحرين  Bahrain
    ("xn--90ais", "cctld", "BY"), // .бел  Belarus
    ("xn--fiqs8s", "cctld", "CN"), // .中国  China (simplified)
    ("xn--fiqz9s", "cctld", "CN"), // .中國  China (traditional)
    ("xn--wgbh1c", "cctld", "EG"), // .مصر  Egypt
    ("xn--e1a4c", "cctld", "EU"), // .ею  EU
    ("xn--node", "cctld", "GE"), // .გე  Georgia
    ("xn--qxa6a", "cctld", "EU"), // .ευ  EU greek
    ("xn--j6w193g", "cctld", "HK"), // .香港  Hong Kong
    ("xn--h2breg3eve", "cctld", "IN"),
    ("xn--h2brj9c", "cctld", "IN"), // .भारत  India
    ("xn--h2brj9c8c", "cctld", "IN"),
    ("xn--mgbgu82a", "cctld", "IN"),
    ("xn--rvc1e0am3e", "cctld", "IN"),
    ("xn--mgbbh1a", "cctld", "IN"),
    ("xn--xkc2dl3a5ee0h", "cctld", "IN"),
    ("xn--fpcrj9c3d", "cctld", "IN"),
    ("xn--gecrj9c", "cctld", "IN"),
    ("xn--s9brj9c", "cctld", "IN"),
    ("xn--45brj9c", "cctld", "IN"),
    ("xn--mgbbh1a71e", "cctld", "IN"),
    ("xn--mgba3a4f16a", "cctld", "IR"), // .ایران
    ("xn--mgba3a4fra", "cctld", "IR"),
    ("xn--4dbrk0ce", "cctld", "IL"), // .ישראל
    ("xn--mgbc0a9azcg", "cctld", "MA"), // .المغرب
    ("xn--l1acc", "cctld", "MN"), // .мон
    ("xn--mgbx4cd0ab", "cctld", "MY"), // .مليسيا
    ("xn--mgbah1a3hjkrd", "cctld", "MR"),
    ("xn--mix891f", "cctld", "MO"), // .澳門
    ("xn--mix082f", "cctld", "MO"),
    ("xn--clchc0ea0b2g2a9gcd", "cctld", "SG"), // .சிங்கப்பூர்
    ("xn--3e0b707e", "cctld", "KR"), // .한국
    ("xn--mgberp4a5d4ar", "cctld", "SA"), // .السعودية
    ("xn--ygbi2ammx", "cctld", "PS"), // .فلسطين
    ("xn--80ao21a", "cctld", "KZ"), // .қаз
    ("xn--mgb9awbf", "cctld", "OM"), // .عمان
    ("xn--mgbai9azgqp6j", "cctld", "PK"), // .پاکستان
    ("xn--mgbai9a5eva00b", "cctld", "PK"),
    ("xn--90a3ac", "cctld", "RS"), // .срб
    ("xn--p1ai", "cctld", "RU"), // .рф
    ("xn--mgbpl2fh", "cctld", "SD"), // .سودان
    ("xn--mgbtx2b", "cctld", "IQ"), // .عراق
    ("xn--ogbpf8fl", "cctld", "SY"), // .سورية
    ("xn--kprw13d", "cctld", "TW"), // .台湾
    ("xn--kpry57d", "cctld", "TW"), // .台灣
    ("xn--mgbtf8fl", "cctld", "IR"),
    ("xn--pgbs0dh", "cctld", "TN"), // .تونس
    ("xn--mgbaam7a8h", "cctld", "AE"), // .امارات
    ("xn--mgb2ddes", "cctld", "YE"), // .اليمن
    ("xn--j1amh", "cctld", "UA"), // .укр

    // ─────────────── IDN sponsored / generic (punycode) ───────────────
    ("xn--vermgensberatung-pwb", "gtld", ""), // .vermögensberatung
    ("xn--vermgensberater-ctb", "gtld", ""), // .vermögensberater
    ("xn--unup4y", "gtld", ""), // .游戏
    ("xn--ses554g", "gtld", ""), // .网址
    ("xn--rhqv96g", "gtld", ""), // .世界
];

/// Unicode  punycode aliases for IDN ccTLDs. Lookups on either form
/// resolve to the same entry. Stored separately so the canonical
/// `TLDS` table doesn't carry duplicate Unicode rows (which would
/// inflate `tld_list()` output and require dedup).
pub const IDN_ALIASES: &[(&str, &str)] = &[
    // (unicode_form, xn--punycode_form)
    ("中国", "xn--fiqs8s"),
    ("中國", "xn--fiqz9s"),
    ("香港", "xn--j6w193g"),
    ("भारत", "xn--h2brj9c"),
    ("ایران", "xn--mgba3a4f16a"),
    ("ישראל", "xn--4dbrk0ce"),
    ("한국", "xn--3e0b707e"),
    ("السعودية", "xn--mgberp4a5d4ar"),
    ("рф", "xn--p1ai"),
    ("台湾", "xn--kprw13d"),
    ("台灣", "xn--kpry57d"),
    ("укр", "xn--j1amh"),
    ("مصر", "xn--wgbh1c"),
    ("ею", "xn--e1a4c"),
    ("გე", "xn--node"),
    ("ευ", "xn--qxa6a"),
    ("مليسيا", "xn--mgbx4cd0ab"),
    ("澳門", "xn--mix891f"),
    ("сингапур", "xn--clchc0ea0b2g2a9gcd"),
    ("بھارت", "xn--mgbbh1a71e"),
    ("امارات", "xn--mgbaam7a8h"),
    ("اليمن", "xn--mgb2ddes"),
    ("сербия", "xn--90a3ac"),
    ("срб", "xn--90a3ac"),
    ("عراق", "xn--mgbtx2b"),
    ("سورية", "xn--ogbpf8fl"),
    ("سودان", "xn--mgbpl2fh"),
    ("عمان", "xn--mgb9awbf"),
    ("پاکستان", "xn--mgbai9azgqp6j"),
    ("تونس", "xn--pgbs0dh"),
    ("الجزائر", "xn--lgbbat1ad8j"),
    ("البحرين", "xn--mgbcpq6gpa1a"),
    ("بيل", "xn--90ais"),
    ("мон", "xn--l1acc"),
    ("游戏", "xn--unup4y"),
    ("网址", "xn--ses554g"),
    ("世界", "xn--rhqv96g"),
    ("vermögensberatung", "xn--vermgensberatung-pwb"),
    ("vermögensberater", "xn--vermgensberater-ctb"),
];

/// Snapshot identifier  bump when the embedded list changes.
pub const SNAPSHOT_VERSION: &str = "iana-root-2024Q4";
