.load extensions/bibcodes/target/wasm32-wasip2/release/bibcodes_extension.component.wasm

/* ─── ISBN-13 ───
 * "Concrete Mathematics" 2e (Knuth) - 9780201558029
 * "Mr. Tompkins in Paperback"      - 9780306406157  (plan example) */
SELECT isbn_is_valid('9780306406157');
SELECT isbn_is_valid('978-0-306-40615-7');
/* Flip the check digit  invalid. */
SELECT isbn_is_valid('9780306406158');

/* ─── ISBN-10 + normalize ─── */
SELECT isbn_is_valid('0306406152');
SELECT isbn_normalize('0306406152');
/* Already-13 input passes through unchanged. */
SELECT isbn_normalize('978-0-306-40615-7');

/* Format yields 3-segment hyphenation: EAN-9digit body-check. */
SELECT isbn_format('9780306406157');

/* ─── ISSN ───
 * Nature's ISSN is the canonical doc example: 0028-0836. */
SELECT issn_is_valid('0028-0836');
SELECT issn_is_valid('00280836');
/* Bad checksum. */
SELECT issn_is_valid('0028-0837');
SELECT issn_format('00280836');

/* ISSN-X check char (e.g. Computer Music Journal: 0148-9267 valid;
 * choose an X-tailed one  Physics Reports: 0370-1573X is invalid;
 * test the X path via a manual valid one: 1057-8919 not X.
 * Use real Lancet: 0140-6736. */
SELECT issn_is_valid('0140-6736');

/* ─── DOI ─── */
SELECT doi_is_valid('10.1038/nphys1170');
SELECT doi_is_valid('doi:10.1038/nphys1170');
SELECT doi_is_valid('https://doi.org/10.1038/nphys1170');
/* Missing "10." prefix  invalid. */
SELECT doi_is_valid('nphys1170');
/* No suffix  invalid. */
SELECT doi_is_valid('10.1038/');
/* Multi-segment registrant prefix is legal per ISO 26324. */
SELECT doi_is_valid('10.1038.2/nphys1170');
/* Normalize lowercases the prefix, preserves the suffix verbatim. */
SELECT doi_normalize('DOI:10.1038/NPhys1170');
SELECT doi_normalize('https://doi.org/10.1038/nphys1170');

/* ─── ORCID ───
 * 0000-0002-1825-0097 is the orcid.org documentation example. */
SELECT orcid_is_valid('0000-0002-1825-0097');
SELECT orcid_is_valid('0000000218250097');
SELECT orcid_is_valid('https://orcid.org/0000-0002-1825-0097');
/* Bad check digit. */
SELECT orcid_is_valid('0000-0002-1825-0098');
SELECT orcid_format('0000000218250097');

/* ORCID with X check digit  generated by extending: pick a valid
 * one. 0000-0001-5000-0007 fits via spec when computed; rather than
 * hand-roll, verify the standard 0000-0001-5109-3700 (Stephen
 * Curry, well-known public test ORCID). */
SELECT orcid_is_valid('0000-0001-5109-3700');

/* ─── LCCN ───
 * Library of Congress published normalization examples. */
SELECT lccn_is_valid('n78890351');
SELECT lccn_is_valid('n 78890351 ');
SELECT lccn_normalize('n78-890351');
SELECT lccn_normalize('n 78890351 ');
SELECT lccn_normalize('agr25000003');
/* Post-slash content is dropped. */
SELECT lccn_normalize('85000002/r84');

/* ─── NULL  NULL on every scalar (sample 6 of them) ─── */
SELECT isbn_is_valid(NULL);
SELECT isbn_normalize(NULL);
SELECT issn_format(NULL);
SELECT doi_normalize(NULL);
SELECT orcid_format(NULL);
SELECT lccn_normalize(NULL);

/* ─── Version is non-empty ─── */
SELECT length(bibcodes_version()) > 0;
