#!/usr/bin/env python3
"""Verify catalog integrity. Exit non-zero on any drift.

THIN DELEGATOR + sqlink-specific checks. The content-addressed IDENTITY checks
(`wit_contract` == recomputed witcanon digest, the `wit_contract_version` major
cross-check, the built artifact's imported `sqlink:wasm@MAJOR` cross-check, and
— under `--verify-content`/`--strict` — `content_digest` == sha256 of the
deployed .wasm) are delegated to the shared `datalink_tooling.verify` engine
(pip-from-git dependency on tegmentum/datalink), driven by
`tooling/datalink.config.json`. NO duplicated identity/witcanon logic lives here.

This is NEW for sqlink (it had no verify-catalog before): the registry was
generated by `provenance/build_registry.py` from the provenance DB but never
checked back. The identity checks are the baseline; the sqlink-specific
`extra_checks` below validate the OCI publishing-model invariants the registry
already carries, so they don't silently rot:

  * every entry has a `name` and a `version`
  * every entry has an OCI-model `checksum` in `sha256:<hex>` (or the
    `sha256:builtin` / `sha256:unbuilt` sentinels build_registry emits) and a
    `size_bytes`
  * every non-builtin entry has an `artifact_url`

  (Empty `exports` is INTENTIONAL for CLI/dotcmd and vtab-only extensions —
  `*-cli`, `core-dotcmd`, `fts5`, `rtree`, `geopoly`, … — so it is NOT a failure;
  it's reported as an advisory only, never an exit-1.)

NOTE on the two digests (see the checksum reconciliation in the consume report):
  - `checksum`        = `sha256:<hex>` of the OCI-PUBLISHED artifact, recorded
                        from the provenance DB at registry-build time (the OCI
                        publishing model). KEPT as-is.
  - `content_digest`  = bare-hex sha256 of a LOCALLY-PRESENT deployed .wasm under
                        identity.artifacts_dir; the shared scheme interoperable
                        with ducklink + the framework's compute_digest. ADDED by
                        gen.py, enforced only under --verify-content (stamped only
                        where the artifact is present locally).

  python3 tooling/verify-catalog.py
  python3 tooling/verify-catalog.py --verify-content   # + content_digest
  python3 tooling/verify-catalog.py --no-artifacts     # toolchain-free subset

  pip install -r requirements-dev.txt   # or: pip install -e ../datalink/tooling
"""
import re
from pathlib import Path

from datalink_tooling import verify

CONFIG = str(Path(__file__).resolve().parent / "datalink.config.json")

# OCI-model checksum: a real `sha256:<64 hex>`, or build_registry's sentinels
# (`sha256:builtin` for the builtin manager entry, `sha256:unbuilt` for an
# extension whose artifact hasn't been built/published yet).
_CHECKSUM_RE = re.compile(r"^sha256:([0-9a-f]{64}|builtin|unbuilt)$")


def sqlink_checks(cfg, entries):
    """sqlink-specific catalog-integrity checks (everything BEYOND the shared
    identity engine): the OCI publishing-model fields the registry carries.
    Receives the FULL registry entry list; returns issues."""
    issues = []
    advisories = []
    for e in entries:
        n = e.get("name") or "<unnamed>"
        if not e.get("name"):
            issues.append("entry with no `name`")
        if not e.get("version"):
            issues.append(f"{n}: missing `version`")
        ck = e.get("checksum")
        if not ck:
            issues.append(f"{n}: missing `checksum`")
        elif not _CHECKSUM_RE.match(str(ck)):
            issues.append(f"{n}: malformed `checksum` {ck!r} "
                          f"(want sha256:<64 hex> or sha256:builtin/unbuilt)")
        if e.get("size_bytes") is None:
            issues.append(f"{n}: missing `size_bytes`")
        # artifact_url required for published (non-builtin) entries only; the
        # builtin manager entry serves no artifact.
        if not e.get("artifact_url") and e.get("source") != "builtin":
            issues.append(f"{n}: missing `artifact_url`")
        # Advisory only: an empty SQL surface is intentional for CLI/dotcmd and
        # vtab-only extensions. Reported, never a failure.
        if not e.get("exports"):
            advisories.append(n)
    if advisories:
        print(f"advisory: {len(advisories)} entr(ies) with empty `exports` "
              f"(CLI/dotcmd/vtab-only, expected): {', '.join(sorted(advisories))}")
    return issues


if __name__ == "__main__":
    verify.main(config=CONFIG, extra_checks=[sqlink_checks])
